### ISSUE TITLE
Add more screenshots

### ISSUE THREAD

**Issue by claremacrae** [obsidianmd/obsidian-help#202]
### The problem

As someone relatively new to Obsidian, I have really struggled with knowing how to name the different parts of the program, to ask for help.

Lots of explanations seem to come in terms of technical implementation details, rather than things visible to users.

### The realisation

I recently discovered that the online Help does have quite good descriptions of the areas of the program.

But none of the sections has any images to show what they are talking about - which means people need to read the words to understand...

I really think these pages marked in red would be significantly more useful if there were small screenshots showing the relevant area of the UI... 

<img width="637" alt="image" src="https://user-images.githubusercontent.com/4840096/142000282-577e1b79-137f-416e-b40b-76e43dcad649.png">

### Offer of help

Hi @ericaxu Would you like a hand with this? I would be happy to spend some time creating the images and tweaking the content, if I could be confident there was interest in it...

**Comment by ericaxu** [comment]
There are some screenshots but not a lot in the help, we're trying to minimize the size of it because it gets bundled with the app and every update. Eventually we want to separate the test vault which is a small, image free vault that contains the essential information from an online, comprehensive, but media heavy vault.

For now I think the docs are doing fine, since the audience is still mostly technical. Moving forward, we'll bring on a pro technical writer to revamp it to make it more friendly to average users.

**Comment by ericaxu** [comment]
Will add more screenshots after the new UI update gets more stable. Thanks for opening the issue!

**Comment by odigity** [comment]
Is this something I could help with?  I just discovered Obsidian today and am going through the docs systematically to learn it, so I could easily start taking screenshots of the relevant components as I discover them myself...

I'm on Ubuntu using the latest .deb (1.4.14) and the default theme, as I haven't gotten to the themes section yet.  :)

**Comment by claremacrae** [comment]
To anyone else who, like me, was super excited to see this marked as completed...

In #592 it says:

> Close https://github.com/obsidianmd/obsidian-help/issues/202 as individual issues will be needed for in-need screenshot areas

So this being marked as completed is a confusing hithub-ism - as this actually hasn't been done - but seems to be going to be replaced by a smaller, more focussed set of issues for different areas....

@sigrunixia May I suggest this particular request is changed from 'completed' to 'won't do' or similar....

**Comment by sigrunixia** [comment]
Can do when the PR is fully in. Sorry for the confusion. :) I wish Github did have other closing tags.

Also, I am open to any suggestions of where to place images in the meantime.

**Comment by claremacrae** [comment]
Hi @sigrunixia,

Ah right - thank you.

I guess the screenshot at the top where I showed what I had found to be most problematical searching for, now looks like this... In particular, I feel the 4 areas under 'Workspace' would each benefit from screenshots:

![image](https://github.com/obsidianmd/obsidian-help/assets/4840096/6a3f2501-fd77-4e52-8907-243683f22b2d)

I still find things a lot harder to find in Mobile than Desktop...

But the above sticks to the spirit of my original (and quite specific) request...

**Comment by sigrunixia** [comment]
So I can keep track of where I am..

- [ ] Workspaces
	- [x] Desktop
	- [ ] Mobile
- [ ] Sidebars
	- [x] Desktop
	- [ ] Mobile
- [x] Ribbon
	- [X] Desktop
	- [X] Mobile
- [ ] Status Bar
	- [ ] Desktop
	- [ ] Mobile

**Comment by sigrunixia** [comment]
With #614 I would consider this tentatively done as a first pass (and it's published on the site now). I am not entirely happy with Status Bar (which I ended up removing some images from) and Workspaces, but I think those may need a more thorough overhaul.
