### ISSUE TITLE
同步的空间容量和单文件限制，在中文帮助中有错误

### ISSUE THREAD

**Issue by jasoncym** [obsidianmd/obsidian-help#385]
![image](https://user-images.githubusercontent.com/53342853/214134637-950e2728-a0cb-419e-8267-437f3299d299.png)
![image](https://user-images.githubusercontent.com/53342853/214134682-3c62cbdf-a27b-4c87-bfc0-ec89119fd2a3.png)
中文帮助和英文帮助的空间容量有区别，一个4g，一个10g

**Comment by ericaxu** [comment]
Just published and should be fixed!
