### ISSUE TITLE
Clarify that footnotes don't auto-render in Live Preview

### ISSUE THREAD

**Issue by trainbuffer** [obsidianmd/obsidian-help#399]
https://help.obsidian.md/How+to/Format+your+notes#Footnotes should clarify that footnotes don't auto-render in/only using Live Preview mode. Bug reports and confusion (forum and Discord) arise because the documentation here isn't clear. I'm guessing it's from before Live Preview was a mode? See > 

https://forum.obsidian.md/t/inline-footnotes-reproduced-as-superscript-no-footnotes-working-in-live-preview/54284
https://forum.obsidian.md/t/live-preview-add-support-for-footnotes/28416/23

**Comment by trainbuffer** [comment]
Poking around the docs,

**Comment by marcusolsson** [comment]
Hi @trainbuffer! 👋 

We're currently reworking docs for Editing and formatting, so this might look different, but we'll be sure to address your feedback in the coming refactor.

Thank you!

**Comment by trainbuffer** [comment]
Hi! Yeah, I know there's a lot to go through. Will reach out again if something bubbles up - feel free to tell me the same thing next time. (^_-)Good hunting 🦾On Feb 21, 2023, at 17:25, Marcus Olsson ***@***.***> wrote:﻿
Hi @trainbuffer! 👋
We're currently reworking docs for Editing and formatting, so this might look different, but we'll be sure to address your feedback in the coming refactor.
Thank you!

**Comment by ericaxu** [comment]
Added in https://github.com/obsidianmd/obsidian-help/commit/0e34cae3701608b3117028fef4eb9455709b0c1e
