### ISSUE TITLE
Undocumented (unintended?) way to embed a list 

### ISSUE THREAD

**Issue by colintedford** [obsidianmd/obsidian-help#439]
This tip about putting a block ID on its own line to embed a list doesn't appear in https://help.obsidian.md/Linking+notes+and+files/Embedding+files (or https://help.obsidian.md/Linking+notes+and+files/Internal+links#Link+to+a+block+in+a+note where it's less applicable). It seems to not work well with autosuggest, so maybe it's not a deliberate feature.

> If you add an empty new line between the list and your block id, it will embed the entire list.
> ```
> - list
> - list
> 
> ^my-id
> ```
> and then embed with `![[note#^my-id]]`

(Source: Luke aka @apfstrudelig1337 @ <https://discord.com/channels/686053708261228577/694233507500916796/1096177255899742261>)

**Comment by ericaxu** [comment]
I think this fixes it https://github.com/obsidianmd/obsidian-help/pull/488
