### ISSUE TITLE
Could the matrix of options for opening links in different ways be in the official docs?

### ISSUE THREAD

**Issue by claremacrae** [obsidianmd/obsidian-help#444]
**Goal: Enable users of the oifficial docs to discover how to click on internal links and control where they open...**

I think it would be helpful to tell users the various modifiers they can use when clicking on internal links, to control how the note is opened.

Thanks to @kometenstaub, I now know that it's the table in here the 1.0.0 release notes:

https://forum.obsidian.md/t/obsidian-release-v1-0-0/44873

Which looks like this...

![image](https://user-images.githubusercontent.com/4840096/233730193-c1091ad1-5aef-4af7-a031-2d11cfd16182.png)

But I think most users won't know this rather specific location.

Perhaps noted it here would be good:

https://help.obsidian.md/User+interface/Use+tabs+in+Obsidian

I am not sure but I think this may be related to #394.

**Comment by ericaxu** [comment]
Added in https://github.com/obsidianmd/obsidian-help/commit/08ebcb7f9f47a5b6a2622dc59711fa84916adbec

**Comment by claremacrae** [comment]
Thank you! ❤️
