### ISSUE TITLE
Improve wording in section about human readable block identifiers

### ISSUE THREAD

**Issue by thibaultmol** [obsidianmd/obsidian-help#447]
We noticed something in the documentation that might cause confusion.

On this page
https://help.obsidian.md/Linking+notes+and+files/Internal+links
It says:
![Screenshot_20230425_184648_Chrome](https://user-images.githubusercontent.com/1010226/234354860-7ba2d7d3-1f3f-4b84-8b92-71bb7adedf20.jpg)

It wasn't 100% clear what "blank space" meant here.

https://discord.com/channels/686053708261228577/694233507500916796/1100470504403501067

**Comment by arghyadeep10** [comment]
Hi @thibaultmol , can you please elaborate a little on the blank space. So the old usage required a blank space before the carat sign but the new one doesn't. So should the documentation be revised focusing on this change in usage.
Thanks
Arghya

**Comment by marcusolsson** [comment]
I think ` ^quote-of-the-day` was previously formatted as a quote, " ^quote-of-the-day", which makes it a little clearer. I think this should be revised a bit to clarify.

@arghyadeep10 No change in usage, it's just unclear what the blank space is referring to here.

**Comment by arghyadeep10** [comment]
@marcusolsson In the current help documentation we have:

```md
You can also create human-readable block identifiers by adding ^quote-of-the-day at the end of a block. Note the blank space before the caret. Now you can instead link to the block by typing [[2023-01-01#^quote-of-the-day]].
```

I think there is no need for a blank space before the caret sign altogether. So should I remove this line and update the documentation accordingly as this line is unclear and creating confusion.

**Comment by marcusolsson** [comment]
I'm reworking this paragraph right now :)

**Comment by marcusolsson** [comment]
Essentially this:

<img width="228" alt="SCR-20230607-kzao" src="https://github.com/obsidianmd/obsidian-help/assets/8396880/363154a7-5e86-4486-a372-93bce36c25ec">
