### ISSUE TITLE
Document that indentation makes code blocks

### ISSUE THREAD

**Issue by colintedford** [obsidianmd/obsidian-help#449]
In Markdown, indenting a paragraph marks it as a code block, but https://help.obsidian.md/Editing+and+formatting/Basic+formatting+syntax#Code+blocks doesn't mention this. We regularly get questions from users who don't know this and are confused when they try to indent (most recently: https://forum.obsidian.md/t/pressing-tab-makes-a-quote/58758).

At the least, it'd be good to mention it in the code block documentation. I'd like to see it somewhere else, too, because the people who get confused by this generally aren't people who would have looked at the documentation for code blocks. I don't know offhand where else it would go — it might be nice to have a section about common gotchas (which would include this, Markdown's collapsing of whitespace, the concept that you should generally put blank lines between blocks, etc). But if it only gets documented in the code block section, at least there'll be something in the official docs I can point to when I answer these questions.

**Comment by ericaxu** [comment]
Thanks for opening issue! I agree this issue comes up frequently.

Do you have any idea what keyword would people usually search it with?

**Comment by colintedford** [comment]
I'd guess "indent" is the most common. The example I linked uses "indent" and "tab".
