### ISSUE TITLE
Refactor Obsidian URI docs

### ISSUE THREAD

**Issue by marcusolsson** [obsidianmd/obsidian-help#457]
When we refactor the Obsidian URI, we should clarify how to link to headings.

https://forum.obsidian.md/t/url-scheme-direct-navigation-to-heading/5907/23?u=koala

**Comment by ericaxu** [comment]
Added in https://github.com/obsidianmd/obsidian-help/commit/78ea9109328fe1f5f9b3bf31c1e8261c761da955
