### ISSUE TITLE
Clarify search terminology

### ISSUE THREAD

**Issue by marcusolsson** [obsidianmd/obsidian-help#462]
We should clarify the language for search better, i.e. query, expression, term, and phrase.

## Proposal

- A _search query_ contains one of more search expressions, such as foo OR (bar -baz).

- A _search expression_ is a combination of an operator, such as OR or - (NOT) and one or many search terms. Both foo OR bar and -baz are search expressions.

- A _search term_ is a word that is used to match something in the note, such as meeting or work.

- A _search phrase_ is multiple words used to match something in the note, such as "wake up neo".

**Comment by ericaxu** [comment]
Hmm I remember this discussion, is the conclusion to refactor the current search docs to apply these?

**Comment by marcusolsson** [comment]
Yeah, to be consistent, it would apply to both the UI and all Help docs, including the Search docs.
