### ISSUE TITLE
Refactor How to

### ISSUE THREAD

**Issue by marcusolsson** [obsidianmd/obsidian-help#464]
The contents of the "How to" section should be moved into relevant topic folders.

- [x] [Add custom styles](https://help.obsidian.md/How+to/Add+custom+styles)
- [x] [Basic note-taking](https://help.obsidian.md/How+to/Basic+note+taking)
- [x] [Capture information](https://help.obsidian.md/How+to/Capture+information)
- [x] [Create notes](https://help.obsidian.md/How+to/Create+notes)
- [x] [Import data](https://help.obsidian.md/How+to/Import+data)
- [x] [Manage attachments](https://help.obsidian.md/How+to/Manage+attachments)
- [x] [Read and edit modes](https://help.obsidian.md/How+to/Read+and+edit+modes)
- [x] [Rename notes](https://help.obsidian.md/How+to/Rename+notes)
- [ ] [Working with multiple notes](https://help.obsidian.md/How+to/Working+with+multiple+notes)
- [x] [Working with multiple vaults](https://help.obsidian.md/How+to/Working+with+multiple+vaults)
- [ ] Delete How to folder

**Comment by ericaxu** [comment]
completed in https://github.com/obsidianmd/obsidian-help/commit/df031f10c68e1ce62ac27e479bd542f65ecee4aa
