### ISSUE TITLE
Refactor Advanced topics

### ISSUE THREAD

**Issue by marcusolsson** [obsidianmd/obsidian-help#465]
The contents of the "Advanced topics" section should be moved into relevant topic folders.

- [x] [Accepted file format](https://help.obsidian.md/Advanced+topics/Accepted+file+formats)
- [x] [Deleting files](https://help.obsidian.md/Advanced+topics/Deleting+files)
- [ ] [Drag and Drop](https://help.obsidian.md/Advanced+topics/Drag+and+Drop)
- [x] [How Obsidian stores data](https://help.obsidian.md/Advanced+topics/How+Obsidian+stores+data)
- [ ] [Insider builds](https://help.obsidian.md/Advanced+topics/Insider+builds)
- [ ] #457

**Comment by ericaxu** [comment]
Finished in https://github.com/obsidianmd/obsidian-help/commit/082546b1d41549a4fdb90ba72492773278c857d9
