### ISSUE TITLE
New tab and new note

### ISSUE THREAD

**Issue by wodecx** [obsidianmd/obsidian-help#477]
When I click the "+" button it will open a new tab. Then I press Ctrl + N on this tab it will create a new note OUTSIDE of the folder. I have changed the settings that create new note in current folder. Why it's not working on the new tab? 

I have a suggestion. Create a new note when click the "+" button rather than open a new tab.

**Comment by joethei** [comment]
Please open feature requests and bug reports on our forum: <https://forum.obsidian.md>

This repository is for our user-facing documentation.
