### ISSUE TITLE
issue with notes sliding over

### ISSUE THREAD

**Issue by ereymundopep** [obsidianmd/obsidian-help#480]
The issue seems to be when I expand a folder, upon each expansion the notes inside slide over to the right. 
Seems it resets when you close the app and reopen only to repeat the same behavior. 

Reference: 
![2e4inkvg](https://github.com/obsidianmd/obsidian-help/assets/109108183/217da3d0-27aa-4046-ad9f-6c7cdf48fb2f)

**Comment by joethei** [comment]
This is the repository for our user facing documentation.
Please post issues on our forum: <https://forum.obsidian.md> and follow the bug report template there.

For this specific issue, update your theme, or switch to default if that does not work.
