### ISSUE TITLE
Addition of Korean Translation (ko)

### ISSUE THREAD

**Issue by BrianJChoi** [obsidianmd/obsidian-help#483]
Hi Obsidian Team.

I am from the Korean Obsidian User Community and I am leading a small team wanting to contribute translating the help docs into Korean, as the number of Korean users is growing.

We are reaching out to get more instructions on how we can start contributing. We have read the instructions on the readme page, but have some questions we want to ask!

**Comment by ericaxu** [comment]
Thank you so much @zachshirow !

@marcusolsson from our team will help you with setting up shortly.

**Comment by BrianJChoi** [comment]
@marcusolsson @ericaxu 
Hi could we get a bit more instructions on what process we should take?
Should we just translate the en help docs Vault and provide it to your team?

We would surely like to get started, but want to get a little more instructions on what we should take note of!

**Comment by marcusolsson** [comment]
Hey @BrianJChoi! 👋 

You can find information on how to add a translation under [Adding a new translation](https://github.com/obsidianmd/obsidian-help#adding-a-new-translation).

You don't need to translate all of it to submit a translation, but we'd prefer if it's more than just a few pages :)

**Comment by ericaxu** [comment]
Hi @BrianJChoi , feel free to start a PR with the instructions given by @marcusolsson . Closing this :)
