### ISSUE TITLE
Persian/Farsi translation of Obsidian Docs

### ISSUE THREAD

**Issue by zachshirow** [obsidianmd/obsidian-help#484]
Hi there dear team of obsidian.

My name is Zachary and I'm from Iran and my language is Persian/Farsi. I wanted to let you know that I would like to contribute in the translation of Obsidian Docs into Persian/Farsi. 

Please let me know if you accept my offer. I'll start whenever is convenient for you.

**Comment by ericaxu** [comment]
Thank you so much @zachshirow !

@marcusolsson from our team will help you with setting up shortly.

**Comment by MPourjam** [comment]
Hi Everybody,
I can also help with the translation. I am also from Iran. It would be nice if I could help by translation.

Best,
Mohsen

**Comment by ericaxu** [comment]
@zachshirow @MPourjam 

Sorry for the late reply! What would be the 2-letter language code for that?

**Comment by MPourjam** [comment]
> @zachshirow @MPourjam
> 
> Sorry for the late reply! What would be the 2-letter language code for that?

The [ISO 639-1:2002][https://en.wikipedia.org/wiki/ISO_639-1] for the Persian(Farsi) is **fa**.

**Comment by ericaxu** [comment]
> > @zachshirow @MPourjam
> > Sorry for the late reply! What would be the 2-letter language code for that?
> 
> The [ISO 639-1:2002](https://en.wikipedia.org/wiki/ISO_639-1) code for Persian(Farsi) language is **fa**.

Add in [95eaed9](https://github.com/obsidianmd/obsidian-help/commit/95eaed935ece718637f5671603dc770a869c42b6). You can find the templates under the `fa/` folder. Thanks!

**Comment by zachshirow** [comment]
> > > @zachshirow @MPourjam
> > > Sorry for the late reply! What would be the 2-letter language code for that?
> > 
> > 
> > The [ISO 639-1:2002](https://en.wikipedia.org/wiki/ISO_639-1) code for Persian(Farsi) language is **fa**.
> 
> Add in [95eaed9](https://github.com/obsidianmd/obsidian-help/commit/95eaed935ece718637f5671603dc770a869c42b6). You can find the templates under the `fa/` folder. Thanks!

Sorry I was not available. I will help with the translation starting in the following day. @ericaxu
