### ISSUE TITLE
Ribbon page is outdated

### ISSUE THREAD

**Issue by colintedford** [obsidianmd/obsidian-help#495]
The [Ribbon page](https://help.obsidian.md/User+interface/Workspace/Ribbon) doesn't mention that the ribbon can be customized, and doesn't describe the mobile interface (mobile documentation in general is very lacking).

Prompted by https://forum.obsidian.md/t/no-ribbon-visible-in-sidebar-in-iphone-app/61585

**Comment by ericaxu** [comment]
Good catch!

**Comment by ericaxu** [comment]
Added in https://github.com/obsidianmd/obsidian-help/commit/3294dcae8ebbf30f50257e247b35d6582baa573f
