### ISSUE TITLE
Unable to underscore a text

### ISSUE THREAD

**Issue by corporate-rat** [obsidianmd/obsidian-help#499]
Dear Obsidian, 

thats already more than 5 month, I am writing daily statuses in chat in a form of:

> 
> [Yesterday](https://github.com/obsidianmd/obsidian-help/issues/new): what was done
> [Today](https://github.com/obsidianmd/obsidian-help/issues/new): what was planned
 
And i'm using underscored text (without links) for outlining significant places of the message.
I know that markdown community do not appreciate underscored-not-url text and propose `<u>`to use this`</u>` kind of formatting.

I'm using that style deliberatively and for a long time: I believe that seeing underscored text, people, who is in chat, feel the urge for the consuming new information, similar like a [pavlov's dog](https://www.youtube.com/watch?v=LlCMwKqlb24), starting to produce more saliva when hearing the bell for food. Not seeing the actual link, people read the actual statuses which follows. remember them better, and by the end of the day I can drive the entire project, just using that simple manipulative approach. 

I'm doing that for good, and I'm asking to add this feature to the Obsidian.md software, so I can continue to do that in a convinient way, having some sort of a diary, at the same time.  

I would feel pretty much ok by having  `_`this`_` type of formatting or similar for underscored text in Obsidian.md, or in the case of impossibility of adding such a tool,  I would have to figuring out the alternative approaches for doing my job, up to changing the place of work, cause I can't refuse to use such a masterpiece like Obsidian.md after I have tried it. 

Best Regards,
Corporate Rat.

**Comment by joethei** [comment]
This is the repository for our user facing documentation.
Please post feature requests on our forum: <https://forum.obsidian.md> and follow the template there.

**Comment by corporate-rat** [comment]
That was heartless 😢
