### ISSUE TITLE
[suggestion] add an option (create shortcut to open vault).

### ISSUE THREAD

**Issue by 7Codez** [obsidianmd/obsidian-help#501]
Obsidian is missing something important.  We desperately need to have a shortcut for every vault.

For example, most of us have 2 vaults. You can add an option named (create shortcat vault). In main menu enter vaults next to (rename and delete vault).

To add a shortcut on a screen, whether computers or phones (and this is a very easy thing to do in programming 👏).

**Comment by joethei** [comment]
This is the repository for our user facing documentation.
Please post feature requests on our forum: <https://forum.obsidian.md> and follow the temp there.
