### ISSUE TITLE
Template's {{title}} doesn't work

### ISSUE THREAD

**Issue by acdesigns** [obsidianmd/obsidian-help#503]
I've tried using it in the YAML of a template to no avail. I wondered if it only works out of the YAML frontmatter, but it also does not work. Both the date and time ones work though.

<img width="397" alt="Screenshot 2023-07-05 152456" src="https://github.com/obsidianmd/obsidian-help/assets/59508042/a58a91e5-f899-41f3-9102-5f56701e02e7">
<img width="353" alt="Screenshot 2023-07-05 152518" src="https://github.com/obsidianmd/obsidian-help/assets/59508042/3880bc07-aa3e-4c95-b8dc-9930ae18c9c1">

**Comment by joethei** [comment]
This is the repository for our user facing documentation.
Please post issues on our forum: <https://forum.obsidian.md> and follow the bug report template there.
