### ISSUE TITLE
Quick Switcher mouse/mobile usage is undocumented

### ISSUE THREAD

**Issue by colintedford** [obsidianmd/obsidian-help#505]
The [Quick Switcher documentation](https://help.obsidian.md/Plugins/Quick+switcher) only says you can access it via the hotkey. It doesn't mention the ribbon icon (or command palette).

**Comment by ericaxu** [comment]
Thanks for the issue! Added in https://github.com/obsidianmd/obsidian-help/commit/91935b4080e25d4402869729ac46485e99442685
