### ISSUE TITLE
Graph Zoom Issue

### ISSUE THREAD

**Issue by IosebAlavidze** [obsidianmd/obsidian-help#508]
When zooming out of the entire app (⌘-) while on the graph screen, the graph endlesly zooms out.

https://github.com/obsidianmd/obsidian-help/assets/97808420/fe46d3af-2d08-4a4d-bce9-7b0988a2f48d

The only way to stop the zoom is to close the graph view (which still causes jarring zoom after reopening).

**Comment by joethei** [comment]
This is the repository for our user facing documentation.
Please post issues on our forum: <https://forum.obsidian.md> and follow the bug report template there.
