### ISSUE TITLE
Consolidate language around Properties (metadata, YAML, frontmatter)

### ISSUE THREAD

**Issue by kepano** [obsidianmd/obsidian-help#513]
Change pages to use "Properties" instead of "Metadata". Clarify references to YAML/frontmatter

- [Metadata](https://help.obsidian.md/Editing+and+formatting/Metadata)
- [Glossary](https://help.obsidian.md/Getting+started/Glossary)
- [Tags](https://help.obsidian.md/Editing+and+formatting/Tags)
- [Publish and unpublish notes](https://help.obsidian.md/Obsidian+Publish/Publish+and+unpublish+notes)
- [Social media link previews](https://help.obsidian.md/Obsidian+Publish/Social+media+link+previews)

**Comment by ericaxu** [comment]
Fixed in https://github.com/obsidianmd/obsidian-help/commit/a890d04806c6b33b8fa7e72846011232323e30e6
