### ISSUE TITLE
Custom app icon setting is undocumented

### ISSUE THREAD

**Issue by colintedford** [obsidianmd/obsidian-help#522]
Mystified users: https://forum.obsidian.md/t/what-does-custom-app-icon-in-settings-do/64423

The changelog doesn't say much. I remember seeing discussion about it on Discord but not the details.

**Comment by PeterBeckley** [comment]
How is part of a feature roll-out not adding the documentation for it? (not even six months later?)

**Comment by sigrunixia** [comment]
> How is part of a feature roll-out not adding the documentation for it? (not even six months later?)

Documentation updating is a never-ending battle and could be a full-time job in and of itself. This is particularly challenging for a smaller team, such as what Obsidian has. Will I eventually get to it? Yes, however, my other duties in support come first. 

You are free to submit a PR as well, even if you are not quite sure what the correct process is. We could clarify it in review. Having an extra pair of hands is so invaluable in what documentation we do have thus far.
