### ISSUE TITLE
[suggestion] Add icons to docs

### ISSUE THREAD

**Issue by mdSlash** [obsidianmd/obsidian-help#524]
Can we insert the icons into the docs without mentioning their names, just like this image?

![image](https://github.com/obsidianmd/obsidian-help/assets/128622475/d675f22e-8008-46ab-b634-3450d7a0e90b)

**Comment by mdSlash** [comment]
> Unfortunately it would make the Markdown source mostly unreadable. But it's a great idea! If we can find a way to do it without obscuring the Markdown source we'll definitely be up for it.

Perhaps we could consider adding support for [Nerd fonts](https://www.nerdfonts.com/#home), which include Lucide icons. The following image displays these icons in the Markdown source.

![image](https://github.com/obsidianmd/obsidian-help/assets/128622475/dc5de486-75b5-4a6a-870e-491d38665273)

**Comment by ericaxu** [comment]
> > Unfortunately it would make the Markdown source mostly unreadable. But it's a great idea! If we can find a way to do it without obscuring the Markdown source we'll definitely be up for it.
> 
> Perhaps we could consider adding support for [Nerd fonts](https://www.nerdfonts.com/#home), which include Lucide icons. The following image displays these icons in the Markdown source.
> 
> ![image](https://user-images.githubusercontent.com/128622475/265058231-dc5de486-75b5-4a6a-870e-491d38665273.png)

Thanks for the recommendation!

I don't think it includes Lucide though. Did I miss something?

**Comment by sigrunixia** [comment]
@mdSlash 
I am actively working on this. I'll have some guidance up on how to handle icons soon, as well as some ready to go in attachments. :)
