### ISSUE TITLE
cannot show [toc] catalog info form Typora Markdown file

### ISSUE THREAD

**Issue by MackDing** [obsidianmd/obsidian-help#542]
![image](https://github.com/obsidianmd/obsidian-help/assets/19878893/ffdc480a-7d27-4571-8ded-b6815cd7c578)

cannot show [toc] catalog info form Typora Markdown file 

how to resolve this issue pls ?

![image](https://github.com/obsidianmd/obsidian-help/assets/19878893/447de2c7-9d71-47c3-a8b7-f876bdd817b0)

**Comment by joethei** [comment]
This is not a core feature of Obsidian, you will need a plug-in.


This is the repository for our user facing documentation.
Please ask questions like this in our community: <https://obsidian.md/community>
