### ISSUE TITLE
Suggestion - add mention about possibility use of HTML type comments in obsidian

### ISSUE THREAD

**Issue by danieltomasz** [obsidianmd/obsidian-help#549]
Many other markdown processer (as pandoc) doesnt honour `%%` Obsidian type comments, but Obsidian can use HTML type comments as well (most other markdown processors honour it)
Would it be suitable to mention it in the comments section?

https://help.obsidian.md/Editing+and+formatting/Basic+formatting+syntax

**Comment by Comprehensive-Jason** [comment]
I don't really think that's a good idea, as doing so would open a huge can of worms around the use of HTML for other types of formatting.

HTML can also be used for bold, italics and highlighting with custom colors, just to name a few possible formatting uses. 

Right now the page you linked makes no mention of HTML whatsoever and is geared solely towards explaining Obsidian-native formatting. I think explaining HTML would be best left to a dedicated _HTML in Obsidian_ page that we could link to from _Advanced Formatting Syntax_.

**Comment by ericaxu** [comment]
I agree with @Comprehensive-Jason . We shouldn't imply HTML comment is the way to go, but it's good to include it for completeness.

@sigrunixia , I think it's good to have a page that basically says HTML will be understood, including comments. Maybe a page to replace this: https://help.obsidian.md/Editing+and+formatting/HTML+sanitization

**Comment by sigrunixia** [comment]
I am still working on this and want to included some more commonly used HTML tags (that I usually see questions for on discord), for things that are not included in markdown syntax. I'm being very superficial and surface level about it. 

So far I have... Strikethrough, Underline, Span/Div, and Comment. Anything else that can be thought of that should be included?
