### ISSUE TITLE
Mobile editor - icon to switch between read/edit blocks view

### ISSUE THREAD

**Issue by kfound** [obsidianmd/obsidian-help#566]
On an iPhone 14 pro and using the editor; the floating butting to switch between read / reading view is much too large and blocks the view of the text in the editor. Can there be an option to disable this floating button? I’d prefer a different method to switch between editing/reading modes. Thanks!

**Comment by ericaxu** [comment]
Hi, this is the repo for the help documentation of Obsidian, not Obsidian itself.

If you have any feedback about Obsidian, please go to https://forum.obsidian.md instead, thanks!
