### ISSUE TITLE
Callouts: mention that the Lucide icons available in Obsidian are behind what's on the Lucide site

### ISSUE THREAD

**Issue by trainbuffer** [obsidianmd/obsidian-help#576]
A lot of confusion arises on Discord and the forum when folks try to use Lucide icons from the [Lucide](https://lucide.dev/icons/) site (using `--callout-icon: lucide-ICON-HERE`).

**Suggestion**:
In the [custom callouts section](https://help.obsidian.md/Editing+and+formatting/Callouts#Customize+callouts) of help, make it clear that the icons available to use in Obsidian are a bit behind from what's available on the Lucide site. Either show the current Lucide library that Obsidian is using, point to the latest [change log](https://obsidian.md/changelog/page/3/#:~:text=The-,Lucide,-icon%20library%20has) entry (both more work for you all to keep updated), or point to the [change log](https://obsidian.md/changelog/) in general (more work for users, but folks can usually find `Lucide` mentioned in the first few pages).

**Comment by sigrunixia** [comment]
I'll need a few days to brainstorm with the team the best way to do this, because providing a link you and others would be able to point to would be helpful and go towards increasing the usage of the help docs. 

After looking at the changelings the last mention of Lucide was in [Catalyst release 1.1.14](https://obsidian.md/changelog/2023-02-16-desktop-v1.1.14/). The changelog documentation can always be improved, but I dont think relying upon those is the best.

**Comment by trainbuffer** [comment]
hi! 👋🏼

Yet one more thing to maintain, but another idea is a landing page listing the libraries currently used in Obsidian. Something like:

```
## Obsidian 1.4.13+ is using: 

- Lucide v0.114.0
- Mathjax v.X.X
- Mermaid v.X.X
- Prism.js v.X.X
- ...
```

Thanks for looking into it!

**Comment by sigrunixia** [comment]
This should appear at the next doc update. :) 

https://github.com/obsidianmd/obsidian-help/pull/579/files

**Comment by sigrunixia** [comment]
Also, pictures are worth 1000 words.
<img width="909" alt="CleanShot 2023-09-22 at 00 25 32@2x" src="https://github.com/obsidianmd/obsidian-help/assets/68425372/a1448f49-dfa0-499e-a759-8ad0d32589b7">

**Comment by trainbuffer** [comment]
Excellent! 

We'll have a place to check and point others to, so they can check themselves.

Well done 👏
