### ISSUE TITLE
Arabic Site Logo

### ISSUE THREAD

**Issue by mdSlash** [obsidianmd/obsidian-help#582]
Could we display the logo on the Arabic website, enable 'backlinks,' and update the favicon?

the logo:
![obsidian-lockup-help](https://github.com/obsidianmd/obsidian-help/assets/128622475/89191c67-566e-4b39-adf9-c60853470843)

I was also wondering if there's a better way than asking you to update the files and notes on the Arabic website every time I make changes.

**Comment by sigrunixia** [comment]
@mdSlash I am very, very sorry for the delay. These items have been completed and I show it reflected. Can you confirm?

Also please feel free to ping me if you need anything on the docs updated.
