### ISSUE TITLE
Text is fully selected after drag-and-dropping it

### ISSUE THREAD

**Issue by meecosha** [obsidianmd/obsidian-help#586]
Whenever I'm drag-and-dropping a text block from one file to another in split screen, in the resulting note it appears fully selected, and I have to click again to deselect it. 

I don't see a single reason, why the drag-and-dropped text should be selected, like what would I do with it now? If I made a mistake and want to undo, I would just Ctrl + Z. So this way, every drag-and-drop requires one more click to go further.

**Comment by liamcain** [comment]
Hi, this is the repo for the help documentation of Obsidian, not Obsidian itself.

If you have any feedback about Obsidian, please go to https://forum.obsidian.md instead, thanks!
