### ISSUE TITLE
some plugin setting buttons disappear

### ISSUE THREAD

**Issue by srun007** [obsidianmd/obsidian-help#593]
A problem that some plugin setting buttons disappear

ver：obsidian 1.4.14

![image](https://github.com/obsidianmd/obsidian-help/assets/80263694/5767cbc8-2922-4368-a0e1-8a91ade4dcea)

**Comment by srun007** [comment]
I have found the problem, the plugin 'setting search' cause the problem , shut down that plugin.

**Comment by sigrunixia** [comment]
Please post an issue on the settings search github page. https://github.com/javalent/settings-search

This repo is for Obsidian’s help docs.
