### ISSUE TITLE
Third party sync debugging

### ISSUE THREAD

**Issue by sigrunixia** [obsidianmd/obsidian-help#595]
Link to common debugging resources for third party sync services in https://help.obsidian.md/Getting+started/Sync+your+notes+across+devices

OneDrive: https://support.microsoft.com/en-au/office/choose-which-onedrive-folders-to-sync-to-your-computer-98b8b011-8b94-419b-aa95-a14ff2415e85

**Comment by sigrunixia** [comment]
Need to think about the extent of this one. Does it belong in the help docs?

**Comment by altairrostam** [comment]
Hi @sigrunixia,

I am interested in contributing to this issue. Could you please elaborate on the requirements? Is the task primarily about adding a link to the OneDrive sync documentation, or are there specific syncing issues with OneDrive that need to be addressed as well?

Thank you!
