### ISSUE TITLE
Document simpler autocomplete algorithm for large vaults

### ISSUE THREAD

**Issue by colintedford** [obsidianmd/obsidian-help#597]
Vaults over 10,000 files use a simpler search algorithm in Quick Switcher and perhaps other autocomplete contexts. 
- https://forum.obsidian.md/t/quick-switcher-search-seems-to-behave-differently-and-miss-some-request/56222/3
- https://forum.obsidian.md/t/wiki-link-autocomplete-cannot-do-fuzzy-search-in-large-vault/68972

This can be very confusing if you don't know about it, as pointed out in https://forum.obsidian.md/t/options-to-control-the-quick-switcher-algorithm-above-10-000-files/56861. Ideally the app should make clear what's happening, but at minimum it should be documented at https://help.obsidian.md/Plugins/Quick+switcher and probably https://help.obsidian.md/Linking+notes+and+files/Internal+links.

**Comment by Ali-C-Ila** [comment]
Maybe it can also be documented in the limitations page
https://help.obsidian.md/Obsidian+Sync/Limitations

**Comment by sigrunixia** [comment]
I know we're planning on adjusting this behavior slightly. I'll confirm what the current standards are, and then get this updated. :)
