### ISSUE TITLE
Search syntax for Properties does not specify existing limitations

### ISSUE THREAD

**Issue by sailKiteV** [obsidianmd/obsidian-help#603]
# Issue

## Explanation

The bracket-based Search syntax for Properties currently acts as syntax sugar for an underlying text query against the property name or property values respectively as per the example `[name:value]`, including when using quotation marks or the alternative regex-based syntax for Search. The implementation at present will not return results for property values of properties that are not ultimate of the text type or a list of text values.

The description offered in the [Search properties](https://github.com/obsidianmd/obsidian-help/blob/master/en/Plugins/Search.md#search-properties) heading of the [Search](https://github.com/obsidianmd/obsidian-help/blob/master/en/Plugins/Search.md) page does not point out the limitation, and users may intuitively expect that they should be able to get results that correspond to the underlying plaintext content of a file's Frontmatter regardless of the type associated with a given property.

As an aside, i think the mentioned heading does not adhere to the style guide for the helpsite (usage of "file" instead of "note", as Properties can only exist on Markdown files in vanilla Obsidian, i believe?). The last example in the section also has an accidental semantic duplication "to find returns", where likely only "to find" or "returns" was intended.

## Solution or Objective

Add a disclaimer of some kind to the designated documentation section, indicating that the limitation exists (to be removed if the Search syntax for Properties changes to remove the limitation).

### Example Text

> The syntax described will not return results for values associated with a property that is not of the Text [property type](<https://help.obsidian.md/Editing+and+formatting/Properties#Property%20types>), or a List of Text-type values.

**Comment by liamcain** [comment]
I think this issue can be closed now since Properties search has been improved in Obsidian 1.5 and property values will fallback to text search.

**Comment by sigrunixia** [comment]
Oki doki, closing!
