### ISSUE TITLE
Daily Note "automated note sorting" callout is inaccurate

### ISSUE THREAD

**Issue by colintedford** [obsidianmd/obsidian-help#606]
The date-based subfolder stuff goes in the Format field, not the Folder field. Details in this convo with a user who got tripped up by this: https://discord.com/channels/686053708261228577/707816848615407697/1166207338886209626

I would also rename the callout to something like "Automatic subfolders". "Note sorting" suggests alphabetical/date-based ordering of files.

**Comment by sigrunixia** [comment]
This should be closed by #612
