### ISSUE TITLE
It's not possible to set "double" hotkeys or hotkey combinations like in Sublime Text

### ISSUE THREAD

**Issue by snrbrnjna** [obsidianmd/obsidian-help#607]
Hey there, 

I'm coming from Sublime Text to Obsidian and i want to keep my shortcut or hotkey for toggling the sidebar as it's working in sublime text. There it's possible to specify hotkey combinations, like `{ "keys": ["super+k", "super+b"], "command": "toggle_side_bar" }` which results on macos in `<Cmd-K>, <Cmd-B>`.

That's currently not possible in Obsidian, at least i can't do it. Would love to get help with this or post this here as a feature request.

Thanks!

**Comment by joethei** [comment]
This is the repository for our user facing documentation.
Please post help requests and feature requests on our forum: <https://forum.obsidian.md>

**Comment by snrbrnjna** [comment]
alrigth. thanks, also noted it, and there's already a thread there on this idea: https://forum.obsidian.md/t/multi-key-or-chorded-key-hotkeys/13221
