### ISSUE TITLE
The canvas can’t show the correct mode when switch from heading mode to the entire mode[bug report]

### ISSUE THREAD

**Issue by srun007** [obsidianmd/obsidian-help#608]
the canvas,i switch entire file mode to narrow heading1 mode , then i decide to switch back to the entire file , it's efect at the time. But when i click another markdown file and back to the canvas , it's still the narrow heading1 status?! it should be the entire file mode. I tried many times, still the bug.
![16abf9ae331e10c584a7510d25474e2](https://github.com/obsidianmd/obsidian-help/assets/80263694/8eaaef77-3267-4335-8b1f-3c7fa475e565)

![459c5a44318f42e2bb4d9bdcb6f2cfd|690x301](upload://q2gAJf7rk9CkiYXFCaYfzpqMh3M.png)
![e2f805ee48933e56770eab4106b79a4](https://github.com/obsidianmd/obsidian-help/assets/80263694/c776e7e3-f8da-41e1-b240-08a434968074)
![f78dd16d54473d43433a90d7083fb9e](https://github.com/obsidianmd/obsidian-help/assets/80263694/28b818fb-f690-4799-8536-828aaa99e3b2)

test in the sandbox remain
![459c5a44318f42e2bb4d9bdcb6f2cfd](https://github.com/obsidianmd/obsidian-help/assets/80263694/41e7bb28-7aaf-416c-8bea-e5aa56648d00)

**Comment by joethei** [comment]
This is the repository for our user facing documentation.
Please post issues on our forum: <https://forum.obsidian.md> and follow the bug report template there.
