### ISSUE TITLE
'=>' breakts list/bulletpoints

### ISSUE THREAD

**Issue by diggidong** [obsidianmd/obsidian-help#609]
by adding a `=>` to the end of a bullet pointed list, the previous bulletpoints break/disappear:

example text:
```
* hi
	* hi hi

* hi
	* hi hi
=> hi

* hi
	* hi hi
		* hi
=> hi
```

![image](https://github.com/obsidianmd/obsidian-help/assets/9928172/b8130a0b-8953-46f7-af85-0d715a9f8e7a)

**Comment by joethei** [comment]
This is the repository for our user facing documentation.
Please post issues on our forum: <https://forum.obsidian.md> and follow the bug report template there.
