### ISSUE TITLE
Settings profiles aren't only an Obsidian Sync feature 

### ISSUE THREAD

**Issue by colintedford** [obsidianmd/obsidian-help#611]
The documentation for settings profiles is [on a page about Obsidian Sync settings](https://help.obsidian.md/Obsidian+Sync/Select+files+and+settings+to+sync#Create+a+settings+profile), but that feature isn't specific to Obsidian Sync and is more useful for other sync options.

I think it should have its own page (probably in the "Customization" folder) and be linked to from https://help.obsidian.md/Getting+started/Sync+your+notes+across+devices and perhaps from the Sync page that it's on now.

**Comment by sigrunixia** [comment]
This should be taken care of in #615 and is live now.

**Comment by sigrunixia** [comment]
https://help.obsidian.md/Customization/Config+folders

:)

**Comment by colintedford** [comment]
Wonderful! 😀

Might want to make it an embed on https://help.obsidian.md/Obsidian+Sync/Select+files+and+settings+to+sync the way it is on https://help.obsidian.md/Getting+started/Sync+your+notes+across+devices
