### ISSUE TITLE
File recovery > Recover a snapshot suggestion

### ISSUE THREAD

**Issue by trainbuffer** [obsidianmd/obsidian-help#616]
On desktop when you open File recovery you see this:

<img width="600" alt="Screenshot 2023-11-03 at 13 28 12" src="https://github.com/obsidianmd/obsidian-help/assets/3751726/52f5524a-6e8e-45a2-9f82-8999524bab80">

It's unclear you need to start typing a note name for suggestions to start showing up. I'll write a feature request in the forum to ask that the UI is made clearer here. I wouldn't say regularly, but it has come up a dozen or so times (that I can remember) that people think there are no snapshots, but they just haven't typed anything yet. 

Altering the documentation slightly could be a start.
Here https://help.obsidian.md/Plugins/File+recovery#Recover+a+snapshot the list is:
```
1. Open Settings.
2. In the sidebar, click File recovery under Plugin options.
3. Next to Snapshots, click View.
4. In the upper-right text box, search for the file you want to recover, and then press Enter.
5. Select the snapshot you want to recover.
6. Click Copy to clipboard to copy the snapshot.
7. Paste the snapshot in the original note, or in a new note if you want to compare them.
```
Number four could be changed a bit:

"4. In the upper-**left** text box, start typing the name of the file you want to recover and you'll see a suggestion list. Select the file, press Enter, and you'll see a list of snapshots available."

or something along those lines.

Thanks.

**Comment by sigrunixia** [comment]
Your verbiage was so good, I stole it. :)

**Comment by trainbuffer** [comment]
Looks good. 

I only put the "upper-**left**" in bold because it said "upper-right" before, and the bold probably isn't necessary here, but either way... it's much clearer now!

Cheers!
