### ISSUE TITLE
Date property auto linking is undocumented

### ISSUE THREAD

**Issue by colintedford** [obsidianmd/obsidian-help#618]
Date-type properties automatically link to the corresponding daily note (or maybe to any page with that name?) but that's not documented in the description of the date type in https://help.obsidian.md/Editing+and+formatting/Properties#Property+format.

I vaguely recall that these aren't "real" links that show up in the graph (tho I may be mistaken, or that may have changed). If they differ in some way from normal links, that should be documented too. 

It would also be nice to have headings for the types so we can link directly to them, but maybe that would be too much formatting.

**Comment by sigrunixia** [comment]
I have just Published a fix for the first and have added "With the [[Daily notes]] plugin enabled, the date property will additionally function as an internal link to the corresponding daily note for that date."

For the second ask, we do have this: https://help.obsidian.md/Editing+and+formatting/Properties#Property+types

Is the desire to have everything in its own section to allow for more and future expansion on what each property type can do?

**Comment by sigrunixia** [comment]
Also, here as well. https://help.obsidian.md/Plugins/Daily+notes#Daily+notes+and+properties

**Comment by colintedford** [comment]
> I have just Published a fix for the first and have added "With the [[Daily notes]] plugin enabled, the date property will additionally function as an internal link to the corresponding daily note for that date."
> 
> For the second ask, we do have this: https://help.obsidian.md/Editing+and+formatting/Properties#Property+types
> 
> Is the desire to have everything in its own section to allow for more and future expansion on what each property type can do?

No, just ease of linking (and ease of scanning the page to find something specific). For example if someone needs info on date properties, I can give them a link to that instead of to "property types and scroll down a ways". (But I understand if that's header overload.)
