### ISSUE TITLE
[Maint request] Update mermaid

### ISSUE THREAD

**Issue by Fordi** [obsidianmd/obsidian-help#619]
Some of the charts available in the [mermaid documentation](http://mermaid.js.org/intro/) are not usable in Obsidian.

The current mermaid version on npm is @10.6.1.

For ref, the version of Obsidian I have (1.4.16) supports everything but: [`zenuml`](http://mermaid.js.org/syntax/zenuml.html), [`sankey-beta`](http://mermaid.js.org/syntax/sankey.html), and [`xychart-beta`](http://mermaid.js.org/syntax/xyChart.html), which is the one that instigated this issue.

Additionally, in auditing support, I noted that Obsidian's rendering of [`quadrantChart`](http://mermaid.js.org/syntax/quadrantChart.html) in dark mode is difficult to read for lack of contrast - though light mode is fine. e.g.,
![image](https://github.com/obsidianmd/obsidian-help/assets/116676/497be86f-f7d1-4920-9c1a-08c8717996f1)

Peeking into `obsidian.asar` in the deployed app, it looks like there's more to it than just updating the mermaid dep, which I attempted by replacing `lib/mermaid.min.js` and re-packing the asar.

**Comment by joethei** [comment]
This is the repository for our user facing documentation.
Please post feature requests on our forum: <https://forum.obsidian.md> and follow the template there.
