### ISSUE TITLE
Obsidian Settings Change

### ISSUE THREAD

**Issue by sigrunixia** [obsidianmd/obsidian-help#634]
Search for references to old settings locations, and update.

**Comment by sigrunixia** [comment]
**List of Pages to Update**
- https://help.obsidian.md/Obsidian+Publish/Set+up+Obsidian+Publish
- https://help.obsidian.md/Obsidian+Sync/Introduction+to+Obsidian+Sync
- https://help.obsidian.md/Customization/Config+folders

**Comment by trainbuffer** [comment]
- https://help.obsidian.md/Getting+started/Update+Obsidian
- https://help.obsidian.md/Concepts/Insider+builds
- https://help.obsidian.md/Licenses+and+payment/Commercial+license (Q1)
- https://help.obsidian.md/Concepts/Interface+language
- https://help.obsidian.md/Obsidian+Sync/Select+files+and+settings+to+sync#Create+a+settings+profile

🫠

**Comment by sigrunixia** [comment]
Thanks for adding! I am certain there is more, but am hoping the IDE can help me catch them.

**Comment by trainbuffer** [comment]
Yeah, I remembered I had a copy of the help documentation (from ~a month ago) saved as a vault. _Search_ for the win! 

Good hunting!
