### ISSUE TITLE
Backups and Obsidian

### ISSUE THREAD

**Issue by sigrunixia** [obsidianmd/obsidian-help#642]
We speak about backups enough that the help docs could use a dedicated article on it. 

This is something I would like assistance with.

**Comment by colintedford** [comment]
The text of our pinned post on Discord is mostly just links but may help with ideas of what to include:

> If you don't already backup your computer, now is a good time to start!
>  
> Easy directions to setup local backups: <https://web.archive.org/web/20200101015933/http://www.worldbackupday.com/en/>
> 
> Links about online backups: ~~<http://www.worldbackupday.com/>~~ Security certificate expired 2024-01-20. Archived version: <https://web.archive.org/web/20240118155850/https://www.worldbackupday.com/en>
> 
> (Note that sync isn’t backup. <https://www.backblaze.com/blog/cloud-backup-vs-cloud-sync/>)

Some other ideas that could be included:
- Links to the File Recovery page and the Sync versioning page (but also making clear those those are conveniences, not appropriate as main backups).
- Notes Are Just Files™ and should be included in the device's regular backups (and if you don't already have regular backups you should set some up ASAP!).

**Comment by sigrunixia** [comment]
Expected area:
Getting Started/Back up your Obsidian Files
