### ISSUE TITLE
How to use the search operator AND and OR (caps) in Obsidian search.

### ISSUE THREAD

**Issue by EdwardKS** [obsidianmd/obsidian-help#645]
How to use AND / OR in parentheses ()?

Please provide a link to the KB page or some examples/instructions.

Thank you!

**Comment by sigrunixia** [comment]
Please leave this open for now.

**Comment by sigrunixia** [comment]
> How to use AND / OR in parentheses ()?
> 
> Please provide a link to the KB page or some examples/instructions.
> 
> Thank you!

We do have this. https://help.obsidian.md/Plugins/Search

Can you detail on the search page what is unclear here? Are the examples too hidden?
