### ISSUE TITLE
Search Full Text in Obsidian Help (https://help.obsidian.md)

### ISSUE THREAD

**Issue by EdwardKS** [obsidianmd/obsidian-help#646]
Besides looking for text in titles, is there a method to search within the main text of the help articles?

**Comment by sigrunixia** [comment]
Sadly not. Obsidian Publish does not have in-note text support yet. Only file names, header names, and aliases. You can download a copy of the help vault from this repository, however.

Use https://download-directory.github.io and give it this link (for English): https://github.com/obsidianmd/obsidian-help/tree/master/en

**Comment by EdwardKS** [comment]
Thank you!
