### ISSUE TITLE
Search limitations of Publish are undocumented

### ISSUE THREAD

**Issue by colintedford** [obsidianmd/obsidian-help#647]
Publish's search feature is limited in ways that I think would surprise most people, but this isn't mentioned in its documentation. Here's some text you can add to [Limitations](https://help.obsidian.md/Obsidian+Publish/Publish+limitations):

```
## Search

Publish only searches page names and headings. Full text search will be added in the [future](https://obsidian.md/roadmap).
```

(I'll add a pull request later if this is still open; I've only done a couple, all thru GitHub, and the process is still a little awkward to me.)

**Comment by sigrunixia** [comment]
Honestly, I'd love to see pull requests from you. :) You make so many good reports and have great suggestions because you interact with so many more users than I can. Any support you need, let me know here or on Discord.

**Comment by colintedford** [comment]
> Honestly, I'd love to see pull requests from you. :) You make so many good reports and have great suggestions because you interact with so many more users than I can. Any support you need, let me know here or on Discord.

All right, I finally did another PR. It's a bit messy; I'm looking at the docs so hopefully the next one will be better (looks like I should have made a branch for each one?), but tips/feedback are more than welcome!

**Comment by sigrunixia** [comment]
> > Honestly, I'd love to see pull requests from you. :) … Any support you need, let me know here or on Discord.
> 
> All right, I finally did another PR. It's a bit messy; I'm looking at the docs so hopefully the next one will be better (looks like I should have made a branch for each one?), but tips/feedback are more than welcome!

Not necessarily. :) Having a change per commit works just as well for 9/10ths of everything here.
