### ISSUE TITLE
Add "Source mode" to the syntax highlighting callout. 

### ISSUE THREAD

**Issue by trainbuffer** [obsidianmd/obsidian-help#657]
https://help.obsidian.md/Editing+and+formatting/Basic+formatting+syntax#Code+blocks

![Screenshot 2024-01-08 at 18 12 47](https://github.com/obsidianmd/obsidian-help/assets/3751726/3bd233eb-a09a-4f6a-a93c-4f6f0791d4cc)

Please add **Source mode** to this callout. e.g. _Source mode and Live Preview don't support..._ 

I pointed out the different highlighting between modes a bit ago and was met with an angry: "I don't use Live Preview". 
:gemmy cry:

Thanks.

**Comment by sigrunixia** [comment]
Oof! Sorry you had to deal with that. I will get this up today.

**Comment by sigrunixia** [comment]
This is now in. Sorry for the wait!
