### ISSUE TITLE
Unclear license situation

### ISSUE THREAD

**Issue by aphedges** [obsidianmd/obsidian-help#658]
This repo (and most others in this organization) does not have a license, which makes it difficult to legally contribute to. According to the GitHub-created site [Choose a License](https://choosealicense.com/no-permission/):

> When you make a creative work (which includes code), the work is under exclusive copyright by default. Unless you include a license that specifies otherwise, nobody else can copy, distribute, or modify your work without being at risk of take-downs, shake-downs, or litigation. Once the work has other contributors (each a copyright holder), "nobody" starts including you.

The linked page has more information on the problem. I don't know what the specific solution is here, but as it currently stands, it would likely be a copyright violation just to clone this repo to my computer. If there is an existing license for this content that I could not find, it should probably be linked in the README so others can see what terms the repo is distributed under.

I would very much like to contribute, so I would appreciate if this could be cleared up.

**Comment by sigrunixia** [comment]
> I don't know what the specific solution is here, but as it currently stands, it would likely be a copyright violation just to clone this repo to my computer.

It would not be a copyright violation by cloning and contributing. Publishing the content yourself and claiming you own it and wrote it, would be a violation. Currently, the repository is operated under fair use, and at this time we are not going to add any specific licensure. That may change in the future.

**Comment by aphedges** [comment]
@sigrunixia, thanks for clarifying! I don't think fair use works that way, but your comment at least assures me I can clone, modify, and contribute to this repository without getting in legal trouble.
