### ISSUE TITLE
The vault icon has wrong color in dark mode

### ISSUE THREAD

**Issue by TheOne04** [obsidianmd/obsidian-help#662]
The vault icon stays dark even in dark mode unlike the other icons:
![image](https://github.com/obsidianmd/obsidian-help/assets/64768475/e560a354-b420-4c32-b86f-e7ec5cbc81eb)

Page referenced:
https://help.obsidian.md/User+interface/Ribbon#Actions

It is probably because of this line:
https://github.com/obsidianmd/obsidian-help/blob/6887334b32b663d8c869affaa5de149afb565dbf/en/publish.css#L10

Because the vault icon is an obsidian icon  and not one from lucide. 

I was thinking of making a PR with something like this:

```css
.theme-dark img[src*="lucide"], img[src*="obsidian-vault"] {
```

but thought this might not be the best way to do it.

**Comment by TheOne04** [comment]
It's not just the vault icon, I came across another icon that has the same issue:
![image](https://github.com/obsidianmd/obsidian-help/assets/64768475/f552580a-51df-4620-b076-8d989994a464)

Probably icons like these should be renamed to add a common prefix?

**Comment by sigrunixia** [comment]
This should now be fixed. :)

**Comment by I-Pch** [comment]
I'm sorry but I've got to ask 😇 : Would the change here have some side-effects on Obsidian's Logo and the website's title colors at the top ? 😊 

I just filed a BR on the forum regarding this: https://forum.obsidian.md/t/obsidian-help-website-small-visual-bug-logo-and-title-in-dark-mode/76501 

(I wasn't sure where to submit it 😊 )

**Comment by sigrunixia** [comment]
It did. I didn’t realize that our logos and titles had the same naming conventions. A bad oversight on my part, really.

I will rename the icons and further scope the CSS today, and that should fix it.
