### ISSUE TITLE
The error message for "Email cannot be empty." is not properly aligned with the Log in dialog.

### ISSUE THREAD

**Issue by kimdigital** [obsidianmd/obsidian-help#663]
Steps to reproduce the issue:
1. Click on the Gear icon in the bottom-left corner.
2. Select the General tab in the Settings modal.
3. Click on Log in button under the Account section & next to "Your account" heading.
4. Leave the Email & Password fields empty and hit enter.
5. Ta-da!
![image](https://github.com/obsidianmd/obsidian-help/assets/157779418/6b283086-a664-4c94-b1cc-226c4e35e48d)

**Comment by sigrunixia** [comment]
This is the Obsidian Help documentation repository. Bug reports for the application can be reported here: https://forum.obsidian.md/c/bug-reports/7
