### ISSUE TITLE
Add "Optimize Mac Storage" details to the iCloud Drive section

### ISSUE THREAD

**Issue by trainbuffer** [obsidianmd/obsidian-help#664]
At the top of https://help.obsidian.md/Getting+started/Sync+your+notes+across+devices, there's a callout about _Dealing with on-demand cloud storage_. That's good. 

A bit farther down in the iCloud Drive section: https://help.obsidian.md/Getting+started/Sync+your+notes+across+devices#iCloud+Drive there's a !note callout. Adding something to that along the lines of: 

> If you plan to sync your Obsidian vault using iCloud Drive on macOS, be sure to disable "Optimize Mac Storage" in iCloud Drive's settings. If this is enabled, iCloud Drive could offload your files, making them unusable by Obsidian, which may result in unexpected behavior.

could _maybe_ help. I understand there can't be a support document about keeping files local for every sync service, but this issue with iCloud comes up **a lot** in Discord and the forum. 

(Another issue is iCloud Drive's option to sync the _Desktop & Documents_ folders, but as far as I know, that's not enabled by default and only tends to come up if someone is using Obsidian Sync and the vault happens to be in one of those locations.)

**Comment by sigrunixia** [comment]
This should now be reflected. 

> (Another issue is iCloud Drive's option to sync the Desktop & Documents folders, but as far as I know, that's not enabled by default and only tends to come up if someone is using Obsidian Sync and the vault happens to be in one of those locations.)

I'll add something to the Sync docs about this.
