### ISSUE TITLE
Translated help sites are not up to date

### ISSUE THREAD

**Issue by naokiy** [obsidianmd/obsidian-help#701]
The help site for non-English languages is not up to date.
Sites published on Obsidian Publish do not reflect the contents of this repository.

Please refer to this page.

https://publish.obsidian.md/help-ja/%E3%83%A9%E3%82%A4%E3%82%BB%E3%83%B3%E3%82%B9%E3%81%A8%E3%82%A2%E3%83%89%E3%82%AA%E3%83%B3%E3%82%B5%E3%83%BC%E3%83%93%E3%82%B9/Obsidian+Sync

This page correctly reflects the [content merged on July 24, 2021](https://github.com/obsidianmd/obsidian-help/pull/156/files#diff-ce87309859bf12c2cbc0fb553c75e919880c9bbf856336df6d5d4fa4a437bde7R13), but does not reflect the[ content merged on July 29, 2021](https://github.com/obsidianmd/obsidian-help/pull/167/files#diff-ce87309859bf12c2cbc0fb553c75e919880c9bbf856336df6d5d4fa4a437bde7R172). Commits made to this repository after that date are also not found on the help pages.

The help site is not up to date for other non-English languages.

**Comment by sigrunixia** [comment]
I will be checking in with the publish site hosters this week to check that the sites will the most-up-to-date information from the repo.

**Comment by naokiy** [comment]
Is there any progress?

**Comment by sigrunixia** [comment]
My apologies for the delay. I finally received a response and this should now be completed. Can you confirm?

**Comment by naokiy** [comment]
I confirmed it! It appears to be up to date.

Thank you for your response.
