### ISSUE TITLE
Moving File Path of Obsidian Vault on iPhone

### ISSUE THREAD

**Issue by CodeKid2024** [obsidianmd/obsidian-help#703]
Dear Obsidian,

I really love your app; I use it for school a lot!
I was wondering why you can't change the apps vault position on the iOS app. I was attempting to sync my school vault to it through Synology Drive (A local, onsite backup tool), but I cannot change the file position to get it in there. I was just curious if this could be added in the next update. 

Thanks,
CodeKid

**Comment by joethei** [comment]
This is the repository for our user facing documentation.
Please post issues and feature requests on our forum: <https://forum.obsidian.md>

Here is the relevant FR: https://forum.obsidian.md/t/full-file-system-access-for-the-ios-app-open-existing-vault-folder/28266, it's very unlikely that this will change in the foreseeable future.
