### ISSUE TITLE
The order of the navigation menu on sites in other languages is different than on English site.

### ISSUE THREAD

**Issue by HanJaeJoon** [obsidianmd/obsidian-help#707]
I was just trying to translate Korean and realized that the order of navigation menu is different.
It might be hard to understand if the order is mixed.

- English: https://help.obsidian.md/Home
![image](https://github.com/obsidianmd/obsidian-help/assets/31728365/52cf23b2-e931-44bc-9080-4ea9bda023bd)

- Korean: https://publish.obsidian.md/help-ko/Home
![image](https://github.com/obsidianmd/obsidian-help/assets/31728365/7456e1d2-9720-496f-9d31-8e3c3c5c27eb)

**Comment by sigrunixia** [comment]
Hello!

We can fix as when we integrate your changes. When you submit the PR to translate the navigation, can you also indicate in the PR what the Publish order of folders should be?

**Comment by HanJaeJoon** [comment]
@sigrunixia 
I commented in https://github.com/obsidianmd/obsidian-help/pull/719#issuecomment-2053921603
