### ISSUE TITLE
Incompatible with Windows 11 App resizing.

### ISSUE THREAD

**Issue by CodeKid2024** [obsidianmd/obsidian-help#711]
In almost all apps on windows, you can resize the app into a certain area on the screen. Obsidian does not do this. I attend a cyber school, so being able to resize the obsidian window easily on screen is very important to note taking.

**Comment by joethei** [comment]
This is the repository for our user facing documentation.
Please post issues on our forum: <https://forum.obsidian.md> and follow the bug report template there.
