### ISSUE TITLE
"Syncing your vault settings" needs development

### ISSUE THREAD

**Issue by GH4TP** [obsidianmd/obsidian-help#714]
The section "Syncing your vault settings" at https://help.obsidian.md/Obsidian+Sync/Select+files+and+settings+to+sync is underdeveloped and could do with further explanation. 

Using the terms "push" and "pull" might help determin which settings to turn on and off on which device. For example, under the sub heading "Secondary device(s)" the documentation suggests, notionally, settings are "pulled" by using the word "received". Are settings received from the Primary device based on what's been uploaded by the primary device to the remote vault with none of the associated settings switched on on the secondary device? Or do the corresponding (same) settings need to be switched on on the secondary device as on the primary in order to "recieve" ("pull")? Or do the same settings need to be switched on on the Secondary device to receive? Or will turning these settings on on the Secondary device enable it to both "pull "and "push"?

Please reach out if this is unclear

Warm regards

TP

**Comment by sigrunixia** [comment]
Push and Pull is not language known to those outside of the tech community. 

However, I am happy to help make it clearer, and will also accept PR's on this.

Can you detail what exactly is not clear, and offer suggestions that conform with [our style guide](https://help.obsidian.md/Contributing+to+Obsidian/Style+guide)? Alternatively, you can make a PR with your suggestions and we'll work on it there.

**Comment by sigrunixia** [comment]
1.6 changed how sync settings were default. We will need to update this section regardless.

**Comment by GH4TP** [comment]
Hi Rebecca,

I am more than happy to help with documentation by writing or proofreading.
My only requirement is to know, from the developers POV, how a function
works. From there I can translate the tech to intelligible doc aimed
at every-day readers, which complies with your style guide, and fits with
your documentation processes.

Cheers

Tim

**Comment by sigrunixia** [comment]
Wrapped into #772
