### ISSUE TITLE
Local Graph: Incorrect/Outdated Info in the Link Notes Sandbox page

### ISSUE THREAD

**Issue by candideu** [obsidianmd/obsidian-help#717]
Hi there! I'm new to Obsidian, and I'm testing out the Sandbox Vault. I love it overall, but I just wanted to flag some outdated info in the [Link Notes.md](https://github.com/obsidianmd/obsidian-help/blob/master/Sandbox/Guides/Link%20notes.md):

There's a mention of being able to access the local page graph via More options (three dots) at the top-right, but this option appears to be missing:

![image](https://github.com/obsidianmd/obsidian-help/assets/55474996/98a23111-3811-438d-8631-ef3cc410a4c5)

[According to the docs](https://help.obsidian.md/Plugins/Graph+view#Local%20Graph), the user has to use the **Open local graph** command, which, by default, has no shortcut:

![image](https://github.com/obsidianmd/obsidian-help/assets/55474996/55fa0c17-15d3-4f8f-ab52-9686e6360d5d)

**Comment by sigrunixia** [comment]
This was fixed in #651 and has been added to the default Sandbox in app.
