### ISSUE TITLE
Discrepancy between PC Sandbox page and GitHub Sandbox

### ISSUE THREAD

**Issue by candideu** [obsidianmd/obsidian-help#718]
The [No prior experience.md](https://github.com/obsidianmd/obsidian-help/blob/master/Sandbox/Adventurer/No%20prior%20experience.md) Sandbox page appears to have an incomplete sentence in the first paragraph: 

![image](https://github.com/obsidianmd/obsidian-help/assets/55474996/63e5e765-8a6d-4b8b-946a-c715050bca1d)

However, the document in this repo appears to have a complete sentence:

![image](https://github.com/obsidianmd/obsidian-help/assets/55474996/8ce0688f-483f-4c30-ad56-11968b18dcce)

**Comment by sigrunixia** [comment]
Will move this to where we can get this fixed, as it's not a problem with the help repo/docs itself.
