### ISSUE TITLE
Obsidian keeps getting stuck. 

### ISSUE THREAD

**Issue by LucEast** [obsidianmd/obsidian-help#720]
Since v1.5.12 I had some micro-lags in Obsidian. 
I tried to run Obsidian in a restricted mode to try to identify whether a community plugin is responsible for this behavior.
When I reactivated the community plugins and restarted Obsidian, it got stuck. 
Now Obsidian is unusable for me... 
Every time I start Obsidian it gets stuck after like 3 seconds. 
I took a screenshot of the dev console. I hope that this will help to identify the Problem. 
My OS is MacOS 14.4.1 on M1 Pro.

![CleanShot 2024-04-14 at 17 08 57@2x](https://github.com/obsidianmd/obsidian-help/assets/47122750/b4f8fb34-29ce-48a5-8ea2-1c604cf85bc1)

**Comment by joethei** [comment]
This is the repository for our user facing documentation.
You can find our community at https://obsidian.md/community
