### ISSUE TITLE
Unable to parse `=` in Live Preview

### ISSUE THREAD

**Issue by VishrutAggarwal** [obsidianmd/obsidian-help#723]
When "=" symbol is encased in backticks in live preview mode, it is unable to parse it and instead shows an error.

When in focus:
![image](https://github.com/obsidianmd/obsidian-help/assets/71827366/03be2086-b7c5-4a46-8945-f6d8df6d49d7)

When not in focus:
![image](https://github.com/obsidianmd/obsidian-help/assets/71827366/884b9323-c850-4ec8-84ab-08f5b7a6080b)

I didn't see any open issues addressing this so I assume no one came across this (which IS a bit confusing to me)?
If there was any issue addressing this problem already, please let me know, I'll close this issue (apologies in advance).

**Comment by VishrutAggarwal** [comment]
I forgot to add the following information:

- OS: Windows 11
- Obsidian Installer Version: v1.5.3
- Obsidian Version: v1.5.12

**Comment by sigrunixia** [comment]
This is the repository for the Obsidian help documentation repo. 

Your specific issue has to do with the fact that Dataview is trying to process the `=` sign, as that is one of its triggers. You may need to escape the backticks with a `\`. For any further questions on this, please refer to the Dataview repository. https://github.com/blacksmithgu/obsidian-dataview
