### ISSUE TITLE
Callout alias attributed to wrong Callout type

### ISSUE THREAD

**Issue by Gawidev** [obsidianmd/obsidian-help#728]
Extremely small issue :)

Under https://help.obsidian.md/Editing+and+formatting/Callouts#Supported+types

"tldr" is marked as an alias under the "abstract" type example.

In obsidian It's currently an alias for the "note" type

![image](https://github.com/obsidianmd/obsidian-help/assets/95928592/2f06bb6c-59d8-402a-a1af-6d7098e7561a)

It should probably marked as an alias for the "note" type instead.

**Comment by sigrunixia** [comment]
Hello!

Did you try this in the sandbox vault, or with all plugins and themes disabled? I cannot reproduce this.

**Comment by Gawidev** [comment]
I'm starting to think I might have dyslexia.
Please ignore tyty
