### ISSUE TITLE
Timing of editing files

### ISSUE THREAD

**Issue by sigrunixia** [obsidianmd/obsidian-help#733]
Pitfall: Editing settings on one device can cause the loss of earlier edits made on another device

**Comment by sigrunixia** [comment]
@colintedford I think this may be a good inclusion in [conflict resolution](https://help.obsidian.md/Obsidian+Sync/Troubleshoot+Obsidian+Sync#Conflict+resolution) since this is related. 

Thoughts?

**Comment by colintedford** [comment]
Sounds reasonable. I would definitely also mention it in https://help.obsidian.md/Obsidian+Sync/Select+files+and+settings+to+sync (maybe in the "restarts" callout)
