### ISSUE TITLE
Request_uri missing in proxy_pass (nginx proxy) Obsidian Publish configuration documentation

### ISSUE THREAD

**Issue by stephane-klein** [obsidianmd/obsidian-help#737]
The Obsidian Publish documentation contains [here](https://help.obsidian.md/Obsidian+Publish/Set+up+a+custom+domain#NGINX) the following instructions for configuring a Nginx server in proxy mode: 

```
location /my-notes {
  proxy_pass https://publish.obsidian.md/serve?url=mysite.com/my-notes/;
  proxy_ssl_server_name on;
  proxy_set_header Host publish.obsidian.md;
}
```

In my experience, this configuration contains a small error.

The request `https://mysite.com/my-notes/` will work, but the other pages `https://mysite.com/my-notes/foo/` `https://mysite.com/my-notes/bar/` ... will return a 404 error.

Question: am I the only one to have noticed this problem?

To fix this problem, I need to add `$request_uri`: 

```
location /my-notes {
  proxy_pass https://publish.obsidian.md/serve?url=mysite.com/my-notes$request_uri;
  proxy_ssl_server_name on;
  proxy_set_header Host publish.obsidian.md;
}
```

Question: am I the only person to have noticed this lack in the documentation?

Additional note: my Nginx instance runs in a container (I use the Nginx Docker image) and I need to add `resolver 8.8.8.8;` to handle the `no resolver defined to resolve publish.obsidian.md, client` error. I don't understand why 🤔.

My complete configuration looks like this: 

```
server {
    listen 80;
    listen [::]:80;

    resolver 8.8.8.8;

    location / {
      proxy_pass https://publish.obsidian.md/serve?url=docs.value-props.com$request_uri;
      proxy_ssl_server_name on;
      proxy_set_header Host publish.obsidian.md;
    }
}
```

@marcusolsson I see [here](https://github.com/obsidianmd/obsidian-help/commit/5ffe46272f3e41ef069611144028626763e9b810#diff-a0a671ecf9f3053f93ad00b62e7a35fd26496e542361c3d100d6eaefad03697f) it was you who published this configuration, what do you think of this proposed correction?

Best regards,
Stéphane

---

Crossposted on Obsidian Forum: https://forum.obsidian.md/t/request-uri-missing-in-proxy-pass-nginx-proxy-obsidian-publish-configuration-documentation/81469

**Comment by sigrunixia** [comment]
> Question: am I the only person to have noticed this lack in the documentation?

At the time the instructions were first added, this generally worked. However, processes change over time, and different providers have different implementations. The proxy instructions are not meant to be exhaustive. 

I will add this to my next commit.
