### ISSUE TITLE
When i click a  link which anchors to another heading in the pinned file itself, it always open a new tab about this file

### ISSUE THREAD

**Issue by EricWong1994** [obsidianmd/obsidian-help#740]
like the picture below,
I don't want it open a new tab, i want it jump to the heading in the current file.
<img width="1175" alt="image" src="https://github.com/obsidianmd/obsidian-help/assets/48429995/0e078dbd-7c9c-42ad-8ebb-3c189860d042">

**Comment by sigrunixia** [comment]
Hello, This is the repository for our Help documentation. Questions like this should go to the Obsidian Community (https://obsidian.md/community).
