### ISSUE TITLE
Sync log is undocumented

### ISSUE THREAD

**Issue by colintedford** [obsidianmd/obsidian-help#741]
Unless I'm overlooking it, Sync's very useful log is not documented. 

Existing issues about specific aspects of the log:
- #730 
- #732

**Comment by sigrunixia** [comment]
Merging the sync log issues into this thread for cleanup. 

## 730 

Different messages, such as accepted, server pushed, etc, have different meanings. This should be documented to users understand what they represent.

## 741 

Add that the "Sync log is not persisted between sessions, or between machines"
