### ISSUE TITLE
Insert table command and (new) Live Preview table use missing from Help documentation 

### ISSUE THREAD

**Issue by trainbuffer** [obsidianmd/obsidian-help#746]
Looking at <https://help.obsidian.md/Editing+and+formatting/Advanced+formatting+syntax#Tables> and searching the Help site, I don't see mention of the `Insert table` command or anything about using the new Live Preview table interface. There's also the right-click context menu -> Insert table.  

I think a lot of the information from the change log, https://obsidian.md/changelog/2023-12-26-desktop-v1.5.3/, and later posts, could be copied and pasted into the Help documentation. Or maybe a new Help page specifically dealing with Tables and linked from the brief section in _Advanced formatting syntax_?

**Comment by sigrunixia** [comment]
I need to think about the extent of what should be explained in length for tables, but I will bandaid this and include the most pertinent things.
