### ISSUE TITLE
Install Obsidian on Windows using WinGet

### ISSUE THREAD

**Issue by Nachoo06** [obsidianmd/obsidian-help#755]
1. In command prompt, run the following command to install Obsidian:
   `winget install Obsidian.Obsidian`
2. Open Obsidian by double-clicking the desktop icon.

**Comment by sigrunixia** [comment]
Our help docs will cover the methods of installation in the releases we maintain in our repo. https://github.com/obsidianmd/obsidian-releases/releases

I suggest adding a ❤️ and your use case to this feature request, which would allow Winget to then be a benefit of something we actively offer: https://forum.obsidian.md/t/add-obsidian-to-new-windows-store/35655
