### ISSUE TITLE
Searching nested tag segments is undocumented

### ISSUE THREAD

**Issue by colintedford** [obsidianmd/obsidian-help#757]
Can a user search each part of a nested tag independently? The docs don't say. 

(In my brief tests it seems that searching the first segment will find all nested tags that start with it, but searching any other segment won't find nested tags that include it. The same seems true for series of segments: starting from the first works, starting elsewhere doesn't.)

**Comment by sigrunixia** [comment]
Nested tags are not truly nested, but are able to be viewed that way for readability. 

The `#Obsidian/Discord/Offtopic` tag is all one tag, and not `#Obsidian`, `#Discord`, and `#Offtopic`. This could probably be a feature request on the forums that is bumped.

Will clarify in the docs now.
