### ISSUE TITLE
"Select files and settings to sync" contains outdated info

### ISSUE THREAD

**Issue by colintedford** [obsidianmd/obsidian-help#759]
The [recent changes to Sync's default settings](https://obsidian.md/changelog/2024-06-07-desktop-v1.6.2/#:~:text=Obsidian%20Sync) require some updates to https://help.obsidian.md/Obsidian+Sync/Select+files+and+settings+to+sync .

**Comment by sigrunixia** [comment]
Some things to keep in mind for this edit for myself.


- App config and appearance configs will hot reload.
- Obsidian core plugin enabled states don't live reload, but the core plugins that are on will hot reload their settings
- Except graph view, it will not hot reload.
- Appearance settings will be received but will still need a reload to reflect the CSS.
- Add a PSA about: https://docs.obsidian.md/Reference/TypeScript+API/Plugin/onExternalSettingsChange
- Notate in the PSA that usage should be determined by the plugin dev, and may not be appropriate for all plugins.

**Comment by sigrunixia** [comment]
Adding #733 to this one, as it deals with the same page.
