### ISSUE TITLE
Documentation: Obsidian Publish limitations unclear (embedded search results)

### ISSUE THREAD

**Issue by Szune** [obsidianmd/obsidian-help#763]
According to the documentation on embedding search results:
https://help.obsidian.md/Plugins/Search#Embed+search+results+in+a+note

> Obsidian Publish doesn't support embedded search results. To see the example, open Obsidian Help locally inside Obsidian.

But it's not listed as a limitation on the page documenting the limitations of Obsidian Publish:
https://help.obsidian.md/Obsidian+Publish/Publish+limitations

Should this notice be added there as well?

**Comment by sigrunixia** [comment]
This is a good point. I will get this added on the next round of changes. :)

**Comment by sigrunixia** [comment]
Note to self: Update this page as well to remove the search callout and point to publish limitations. https://help.obsidian.md/Obsidian+Publish/Manage+sites#Components
