### ISSUE TITLE
Recommend using the Broken Links plugin to find and fix broken links to files, headings and images

### ISSUE THREAD

**Issue by claremacrae** [obsidianmd/obsidian-help#764]
### Specific broken link

I was going to report this broken link:

![image](https://github.com/obsidianmd/obsidian-help/assets/4840096/98732707-e659-47bc-9e2e-edd4429d2fd8)

in this page...

https://help.obsidian.md/Licenses+and+payment/Catalyst+license

### General solution

I can't recommend the [Broken links plugin](https://github.com/ipshing/obsidian-broken-links) highly enough.

I just installed it in a clone of this vault and it quickly shows places to fix:

![image](https://github.com/obsidianmd/obsidian-help/assets/4840096/5ef95dbf-100c-4b34-86c5-239b0444c44f)

![image](https://github.com/obsidianmd/obsidian-help/assets/4840096/e7c3f24d-2779-4ff1-a2ee-7e5a6fd857b2)

I appreciate it would-be better to run it on one language at a time - I opened the whole thing for expedience...

**Comment by sigrunixia** [comment]
So I got the English ones in #771 today. 

I am not confident enough in the languages of the other ones to try to fix those. So what I will do instead is add checking for broken links into our style guide, and investigate some possible automation options we can employ to help.

So, marked as partially completed. :)

**Comment by claremacrae** [comment]
Brilliant. Thanks very much.
