### ISSUE TITLE
Bold with dot inside is making the following text bold

### ISSUE THREAD

**Issue by mayeenulislam** [obsidianmd/obsidian-help#766]
Here in this GIF, I demonstrated the issue:
![Jun-30-2024 00-35-47](https://github.com/obsidianmd/obsidian-help/assets/4551598/bbdce6ff-f681-4a73-8e01-3020fbd9fbb1)

I disabled all the community plugins. Here is the debug info:

```
SYSTEM INFO:
	Obsidian version: v1.6.5
	Installer version: v1.5.11
	Operating system: Darwin Kernel Version 23.5.0: Wed May  1 20:14:59 PDT 2024; root:xnu-10063.121.3~5/RELEASE_ARM64_T8122 23.5.0
	Login status: not logged in
	Insider build toggle: off
	Live preview: on
	Base theme: light
	Community theme: none
	Snippets enabled: 0
	Restricted mode: on

RECOMMENDATIONS:
	none
```

**Comment by joethei** [comment]
This is the repository for our user facing documentation.
Please post issues on our forum: <https://forum.obsidian.md> and follow the bug report template there.
