### ISSUE TITLE
Callouts: explain syntax with pipe symbol

### ISSUE THREAD

**Issue by Kalimbim** [obsidianmd/obsidian-help#774]
I noticed in Discord \#appearance a notation for Callouts, that includes a pipe symbol with some additional data elements. Is this notation documented?

```
> [!note|data1 data2 data3] title
> content
```

<https://help.obsidian.md/Editing+and+formatting/Callouts> doesn't explain it yet. So it's anyone's guess, how the notation is supposed to work. This is my current understanding:

- By default Callouts do not contain a pipe symbol. `> [!note]` is the minimal form for Callouts. The square brackets only contain an `!` followed by the name of the callout type. 
- If there is a pipe symbol, Obsidian passes everything between the pipe symbol `|` and the closing bracket `]` as a string to the global data attribute `data-callout-metadata` of the Callout's `<div>`. 
- The content of this data attribute is meant to be used with attribute selectors. For example `div[data-callout-metadata~="data2"]` would test for the existence of `data2` in the string.
- Obsidian expects the passed string to be a space separated list of one or more values. (If the Callout contains multiple pipe symbols, every one but the first will be included in the string.)

Please add the notation to Obsidian Help, so that we have an official reference of the intended behavior.

**Comment by trainbuffer** [comment]
While I would definitely like a lot more documentation on Obsidian's unique CSS, I think the `[data-callout-metadata~=""]` usage is beyond the scope of the [customize Callouts help section](https://help.obsidian.md/Editing+and+formatting/Callouts#Customize+callouts). There are numerous examples in the Discord `#appearance` channel, in some themes, the [ITS callouts snippet](https://publish.obsidian.md/slrvb-docs/ITS+Theme/Callout+Adjustments), the [Multi Column callouts snippet](https://obsidian-mcl-docs.netlify.app/02-multi-column/01-multi-column/), etc.

As far as callout structure goes, there's also (via sailKite):
```
/* --- how callouts are structured --- */
.callout
├─.callout-title
│ ├─.callout-icon
│ │ └─svg
│ ├─.callout-title-inner
│ └─.callout-fold
│   └─svg
└─.callout-content
```

that can be adjusted. Should those and how to properly write the CSS to adjust them be included in the help page as well? 

I'm not arguing against better Obsidian CSS documentation, but I'm not sure if this help page is the best spot for it.

**Comment by sigrunixia** [comment]
@trainbuffer is correct. 

We would refer to the forums for this first. You might be able to see if you could get the CSS variables and specific functions to have more details expanded upon in [the developer documentation](https://docs.obsidian.md/Home) but that is a question for that repository.

**Comment by Kalimbim** [comment]
Actually it was [a post on Discord](https://discord.com/channels/686053708261228577/702656734631821413/1260471943476543498) by @trainbuffer that prompted this request:

> You could try something like this:
> ```css
> .callout:is(div[data-callout-metadata*="buttons220"]) {
>    width: 220px;
> }
> ```
> and change the second callout to `[!buttons|float-left-small buttons220|min-0]+`. That seems to work in _this_ case

I was curious about the pipe before "min-0". Was it on purpose or not? And whatever the answer on Discord, how should I know it represents the developers intention?

A simple clarification of valid notations would suffice:

> [!note] title
> this is the default

> [!note|option1 option2 …] title
> set additional options for Callouts that have additional options

Where else can users find the "official" position, if not in Help?

**Comment by Kalimbim** [comment]
> Should those and how to properly write the CSS to adjust them be included in the help page as well?

No. The feature request is not about writing CSS, but about writing valid Obsidian Markdown:

- Is the notation with one pipe symbol valid Obsidian Markdown?
- Is the notation with two or more pipe symbols valid Obsidian Markdown?

Where else but in the official help pages can users learn about official specs for Obsidian flavored Markdown?
