### ISSUE TITLE
Ambigous sentence in Sync obsidian help

### ISSUE THREAD

**Issue by Nachiten** [obsidianmd/obsidian-help#777]
The page is [Local and remote vaults](https://help.obsidian.md/Obsidian+Sync/Local+and+remote+vaults).

In the last paragraph, the following sentence:

> You can connect multiple local vaults to your remote vault.

Is ambigous, because it can imply that I can sync multiple local vaults to the same remote vault **on the same device**. So, I would change the sentence as follows:

> You can connect multiple local vaults *from different devices* to your remote vault.

Do you think this sentence makes sense?

Thank you very much 😄

**Comment by Kalimbim** [comment]
Or maybe rewrite the whole page? It should explain:

- Obsidian stores files in local vaults
- Obsidian can *not* share files in local vaults.
- Obsidian Sync can sync a local vault with a remote vault.
- The same remote vault can be synced with local vaults on an (unlimited?) number of devices
- Syncing nested vaults is a bad idea. (Why?)
- The number of remote vaults one Obsidian account can have depends on the subscribed plan. (Add link to pricing?)
-  A remote vault is deleted after 30(?) days of inactivity.
- Syncing is not backup. Obsidian stores it files in a local vault. The purpose of Obsidian Sync is to sync the local vaults of multiple devices by using a remote vault as intermediary.
- The remote vault is encrypted. If users lose their password, nobody can access the vault. Unused vaults are deleted automatically after … (see above)
- There is no web interface to the remote vault. Remote vaults can only be accessd via Obsidian's app.

**Comment by sigrunixia** [comment]
I will add something to address this in #772

**Comment by sigrunixia** [comment]
Also...

> Is ambigous, because it can imply that I can sync multiple local vaults to the same remote vault on the same device. So, I would change the sentence as follows:

You can, actually. I just wouldn't recommend it. 😢

**Comment by Kalimbim** [comment]
> You can, actually. I just wouldn't recommend it. 😢

Why not? Obsidian Help is where I'd expect to stumble over such recommendations. Like: 

> We recommend to sync a remote vault with only one local vault on each device, because syncing it with multiple vaults on the same device …

**Comment by sigrunixia** [comment]
> > You can, actually. I just wouldn't recommend it. 😢
> 
> Why not? Obsidian Help is where I'd expect to stumble over such recommendations. Like:
> 
> > We recommend to sync a remote vault with only one local vault on each device, because syncing it with multiple vaults on the same device …

When doing docs, it's a balance of making things easy and accessable, versus overly verbose and trying to encounter all edge cases. 

Example, we say sync will take the same data across all devices. So if you add multiple local vaults, it's assumed the data across all local vaults will be synced, for good and for ill. 

What I think I can do though, is add a note about sync exclusions for such a case.
