### ISSUE TITLE
minor typo in help.obsidian.md

### ISSUE THREAD

**Issue by CHOCOLVT** [obsidianmd/obsidian-help#780]
### Discussed in https://github.com/obsidianmd/obsidian-help/discussions/779

<div type='discussions-op-text'>

<sup>Originally posted by **CHOCOLVT** July 16, 2024</sup>
Helloo!

First of all, thank you very much for offering the world such an amazing tool!

I planned to purchase Obsidian Sync so I started reading the doc, which is well designed :)
In the first line of the section [Sync settings are not synced](https://help.obsidian.md/Obsidian+Sync/Select+files+and+settings+to+sync#Sync+settings+are+not+synced) of the page [Select files and settings to sync](https://help.obsidian.md/Obsidian+Sync/Select+files+and+settings+to+sync), I noticed a minor typo: the word "each" appears twice in a row, therefore, I chose to notify you.:
_Sync settings are not synced so that **each each** device can be separately configured according to your needs._

Thank you for all your work!
I really enjoy Obsidian!! <img src="https://github.com/user-attachments/assets/cd901918-295d-47f0-9acf-51009a3d1fb9"  width="25" height="25">

P.S.: I'll definitely try Obsidian Sync. ;)
</div>

**Comment by sigrunixia** [comment]
Hello! We're actually redoing this in #772 to make it something completely different. Thanks for your efforts, however!
