### ISSUE TITLE
v1.6.7 on macOS is SLOW

### ISSUE THREAD

**Issue by samholmes** [obsidianmd/obsidian-help#781]
I restarted my computer yesterday and re-opened Obsidian which auto updated. Now it's unbearably slow and unusable.

**Comment by colintedford** [comment]
This repository is for Obsidian's help documentation.
You can get help, report bugs, and request features at the [forum](https://forum.obsidian.md/).

**Comment by samholmes** [comment]
I've submitted my bug issue here: https://forum.obsidian.md/t/performance-sluggish/85599
