### ISSUE TITLE
On mobile app, can't open a file if it's selected/highlighted/focused.

### ISSUE THREAD

**Issue by JorensM** [obsidianmd/obsidian-help#783]
On the mobile app, when you open a file, and then move back to the folder, the file in the list gets highlighted but you can't open it anymore, unless you open another file, only after that you can open the previous file.

**Comment by sigrunixia** [comment]
This repository is for Obsidian's help documentation.
You can get help, report bugs, and request features at the [forum](https://forum.obsidian.md/).

**Comment by JorensM** [comment]
> This repository is for Obsidian's help documentation. You can get help, report bugs, and request features at the [forum](https://forum.obsidian.md/).

Oops, my bad.
