### ISSUE TITLE
Additional Sync Settings Changes

### ISSUE THREAD

**Issue by sigrunixia** [obsidianmd/obsidian-help#787]
Sorry I didn't have a chance to look this over. I wanted to wrap my head around the pull request review process and haven't had a chance to. I haven't read the live page closely yet but here are a couple bits of feedback.

The heading says "settings" while the body text says "configurations". I would use "settings" because it's simpler and is used in Obsidian's interface, plus it flows better.

I would not use the term "hot reload" — it feels to me like a bit more technical detail/jargon than a user needs. And depending on the font, someone unfamiliar with the term may misread it as "not reload", which would change the meaning of the second sentence.

_Originally posted by @colintedford in https://github.com/obsidianmd/obsidian-help/issues/772#issuecomment-2252000311_

**Comment by colintedford** [comment]
I just noticed that besides the updated info in https://help.obsidian.md/Obsidian+Sync/Select+files+and+settings+to+sync#Reloading+of+settings there is an outdated version in https://help.obsidian.md/Obsidian+Sync/Sync+limitations#Does+Obsidian+Sync+live-reload+my+settings%3F.

**Comment by colintedford** [comment]
Also I would also specifically mention whether or not Community Plugin setting changes require an app reload, since that's a common case where this issue comes up.

**Comment by sigrunixia** [comment]
This is done and GH will say so in a moment. Community plugins were a touchy subject, so I did as light as I could touch on it.
