### ISSUE TITLE
The code block in the quote block cannot be rendered instantly

### ISSUE THREAD

**Issue by hileez** [obsidianmd/obsidian-help#790]
The code block in the quote block cannot be rendered instantly, and too many special symbols need to be escaped, such as the # symbol. Edit mode without paragraph distance and line confusion.
![屏幕截图 2024-08-01 032318](https://github.com/user-attachments/assets/6c46d70a-d1ae-47df-b45a-b82e8b1092f8)
![屏幕截图 2024-08-01 031730](https://github.com/user-attachments/assets/f891ded9-0032-43c4-90be-bb7a6871b729)

**Comment by joethei** [comment]
This is the repository for our user facing documentation.
Please post issues on our forum: <https://forum.obsidian.md> and follow the bug report template there.
