### ISSUE TITLE
Add Sync History Instructions

### ISSUE THREAD

**Issue by sigrunixia** [obsidianmd/obsidian-help#792]
- Current active if Sync Core Plugin is active
- Can be opened via Command palette -> Sync: Show Sync History or via hotkey (default is unset)
- Opens in right sidebar
- Hovering over name shows who lasted edited it.

**Comment by claremacrae** [comment]
I think it's worth noting that even if you are the only person syncing your vault, this Sync History pane is a fantastically convenient mechanism to quickly switch between recently-edited documents, regardless of which of your devices it was last edited on.

It's much more generally useful than a Sync History - it's an Editing History, which was not immediately obvious to me, so likely some others would find the suggestion useful too.

**Comment by sigrunixia** [comment]
I did discover that currently this only shows changes and additions, not deletions. This is due to if a file is clicked, it will be created. I am looking to see if a deletion could be added, as it is a valuable troubleshooting tool. But it likely will not make it to this release.

**Comment by sigrunixia** [comment]
Additionally, obsidian settings changes are not shown in the sidebar.

seems only Notes and attachments
