### ISSUE TITLE
中文帮助文档翻译错误

### ISSUE THREAD

**Issue by zhr-nmlk** [obsidianmd/obsidian-help#795]
在用户界面->快捷键章节中，对非美国用户的提醒，”键盘不局“应为”键盘布局“。

**Comment by sigrunixia** [comment]
感谢您的反馈。应报告应用程序的翻译更新并将其提交到翻译存储库。https://github.com/obsidianmd/obsidian-translations

Thanks for the feedback. Translation updates for the application should be reported and submitted to the translations repository. https://github.com/obsidianmd/obsidian-translations
