### ISSUE TITLE
Sorting of numbers and characters incosistent in folder view

### ISSUE THREAD

**Issue by dwessendorf** [obsidianmd/obsidian-help#796]
If you created folders with numbers and folders with letters, the folders with numbers would be displayed before the folders as seen below:
1
2
A
B

However if you got two folders with a first called 11 and the second folder called 1A then A would be sorted higher than the number as seen below:
1A
1B
11
12

if you mix single digit and double digit you even get something like this
1
1A
2
11

This drastically reduces the abilitiy to create a structured directory tree in Obsidian.
<img width="110" alt="Screenshot 2024-08-16 at 09 13 27" src="https://github.com/user-attachments/assets/0d427709-8e62-4fb1-9d99-d57aa30b0f72">

**Comment by sigrunixia** [comment]
This is the repository for the Obsidian Help documentations. Questions, concerns, and feedback about the application should go to our forums. https://forum.obsidian.md
