### ISSUE TITLE
iCloud on Windows warning is not in the iCloud documentation

### ISSUE THREAD

**Issue by colintedford** [obsidianmd/obsidian-help#797]
The warning about iCloud on Windows doesn't appear in https://help.obsidian.md/Getting+started/Sync+your+notes+across+devices#iCloud+Drive. This is a problem when linking to the iCloud section. 

The issue seems to be because that section is nested under the iPhone/iPad section. Despite that, the iCloud section talks a lot about MacOS.

I suggest restructuring the page. I don't have a complete vision for this, but I think the sections about services (like iCloud) should not be nested under the sections about OSes. All of the info about using a service should be under the service's section. The OS sections can keep their lists of supported sync options (and any other OS- specific, service-agnostic info) and link to them as appropriate.

**Comment by sigrunixia** [comment]
Good ideas. :) I'll ruminate on this.

**Comment by sigrunixia** [comment]
This was closed via #834
