### ISSUE TITLE
Documentation update for Obsidian Sync

### ISSUE THREAD

**Issue by alltiagocom** [obsidianmd/obsidian-help#798]
Please check the original post I create on the forum:
[https://forum.obsidian.md/t/documentation-update-for-obsidian-sync/87290](https://forum.obsidian.md/t/documentation-update-for-obsidian-sync/87290)

**Comment by sigrunixia** [comment]
from the forum post:
In this section of Obsidian Sync:


[Obsidian Help](https://help.obsidian.md/Obsidian+Sync/Troubleshoot+Obsidian+Sync#Move+your+vault+using+the+vault+switcher)

[Troubleshoot Obsidian Sync - Obsidian Help](https://help.obsidian.md/Obsidian+Sync/Troubleshoot+Obsidian+Sync#Move+your+vault+using+the+vault+switcher)

This page lists common issues that you might encounter with Obsidian Sync, and how to address them. Sync your notes across devices#^sync-files-on-demand General Conflict resolution A conflict happens…
I think it’s important to mention that if there’s only one vault on the list, there will be an error:
image

So I believe that we need to

Create a dummy vault first and open it
Move the main vault
Delete the dummy vault.

**Comment by sigrunixia** [comment]
Will check if this should be a bug and fixed.
