### ISSUE TITLE
Seemingly incomplete paragraph in the Sandbox

### ISSUE THREAD

**Issue by Tompouce-onGit** [obsidianmd/obsidian-help#807]
In the Obsidian Sandbox, under `Adventurer/No prior experience`, the first paragraph suddenly stop in the middle of a sentence. It looks like it was accidentally left unfinished.

![Screenshot_2024-09-04_20-59-53](https://github.com/user-attachments/assets/b0504063-fa81-43a7-87c7-0385c7edc972)

**Comment by sigrunixia** [comment]
This issue is within the application alone. Will suggest update internally.

**Comment by sigrunixia** [comment]
This will be fixed in the next release.
