### ISSUE TITLE
[feature request] exposing webhook through obsidian

### ISSUE THREAD

**Issue by 4383** [obsidianmd/obsidian-help#810]
Hey folks,

I'm not sure if this is the right place to ask my question and to request a new feature.
I'm looking for a way to send requests to obsidian, by example to create a new file in a specified vault.
I want to be able to submit a filename and a file content to create that file.

AFAIK, there is yet no webhook capabilities in obsidian and

**Comment by joethei** [comment]
This is the repository for our user facing documentation.
Please ask questions in our community: <https://obsidian.md/community>
For feature request visit our forum: <https://forum.obsidian.md/c/feature-requests/8>

**Comment by 4383** [comment]
ok, thanks for your previous comment. I'm gonna close this PR
