### ISSUE TITLE
Basic Formatting doesn't say how to escape Markdown symbols

### ISSUE THREAD

**Issue by colintedford** [obsidianmd/obsidian-help#812]
I think the Basic Formatting page should explain how to escape Markdown syntax for when people need to use those characters literally. It may also be worth mentioning specifically how to escape numbered list markers (backslash before the period, not before the number), because that's unintuitive.

**Comment by sigrunixia** [comment]
Adding this for my reference.

https://stackoverflow.com/questions/12833093/in-markdown-how-do-i-start-a-line-with-a-number-without-creating-a-list
