### ISSUE TITLE
 Incorrect File Linking in 'Diary' Plugin

### ISSUE THREAD

**Issue by genie0320** [obsidianmd/obsidian-help#813]
Upon activating the core 'Diary' plugin and populating the 'data' property, a small link icon is generated as expected. However, I've encountered the following issues with the generated link button:

- Incorrect File Association: Clicking the link directs the user to a file with an entirely incorrect date.
- File Regeneration: If the incorrectly associated diary file for that date is deleted and the link button is clicked again, a new file is generated for the intended date and is then correctly linked.

![image](https://github.com/user-attachments/assets/7a6df6c2-85a0-4cc7-b98b-1ef684f90739)
![image](https://github.com/user-attachments/assets/bf6f7b72-a6c9-4994-9500-1949a242681e)

**Comment by joethei** [comment]
This is the repository for our user facing documentation.
Please post issues on our forum: <https://forum.obsidian.md> and follow the bug report template there.
