### ISSUE TITLE
ist with http code block format issue

### ISSUE THREAD

**Issue by tonny008** [obsidianmd/obsidian-help#818]
1. list with http code block format not correct in editing mode
    i am a paragraph in list
    ```http
   i am code
    ```
2. ddd

![image](https://github.com/user-attachments/assets/b423e0ea-b842-47f9-8d5f-9cb2f1f0218a)

**Comment by sigrunixia** [comment]
This is the repository for our user facing documentation.
Please post issues on our forum: https://forum.obsidian.md/ and follow the bug report template there.
