### ISSUE TITLE
Can I change the syntax to initiate math mode?

### ISSUE THREAD

**Issue by 5alv1** [obsidianmd/obsidian-help#821]
I need to export the md files I write with obsidian, some of them have math in them but the software I have to use to render doesn't support the ```$$``` syntax, but I have to do ```\\( math \\)```, is there a way to change settings in obsidian so that math preview is shown when I use the latter syntax?

**Comment by sigrunixia** [comment]
This is the repository for our user facing documentation.
Please post issues or questions on our forum: https://forum.obsidian.md/
