### ISSUE TITLE
Use of the deprecated term "search query"

### ISSUE THREAD

**Issue by ya4ept** [obsidianmd/obsidian-help#835]
There is a note in the [style guide](https://help.obsidian.md/Contributing+to+Obsidian/Style+guide#Terms):
> Prefer "search term" over "search query".

However, the manual uses a deprecated term: "search query"

1. https://help.obsidian.md/Plugins/Graph+view
2. https://help.obsidian.md/Plugins/Tags+view
3. https://help.obsidian.md/Extending+Obsidian/Obsidian+URI

![image](https://github.com/user-attachments/assets/97c7f875-f91e-46ff-a98c-3a4d3ce6f3c1)

**Comment by ChineseHamberger** [comment]
As a user of obsidian, I'd like to fix this bug as my first contribution.
