### ISSUE TITLE
Maybe add .canvas to the list of accepted file formats?

### ISSUE THREAD

**Issue by claremacrae** [obsidianmd/obsidian-help#841]
Thank you for your time in completing this issue! 🙌

# What is the problem in the documentation?
_Is it missing something? Is the information incorrect?_

I noticed that the Accepted file formats page does not list `.canvas`.

![image](https://github.com/user-attachments/assets/174bb226-ba69-4b63-9ae3-d0f5e3850ad8)

## Any suggested fixes?
_If it were you handling this issue, what would you do to fix it?_

It feels to me like Canvas is now a file format, and perhaps it should be listed here too...?

# Have any context we can refer to?
_For example, a Discord link, an existing doc site, etc._

https://help.obsidian.md/Files+and+folders/Accepted+file+formats

**Comment by sigrunixia** [comment]
Note to self.. Add it, and include this. https://jsoncanvas.org/docs/apps/

**Comment by claremacrae** [comment]
Awesome - thank you!
