### ISSUE TITLE
Confusing docs of Parameters in Obsidian URI page

### ISSUE THREAD

**Issue by claremacrae** [obsidianmd/obsidian-help#851]
Thank you for your time in completing this issue! 🙌

# What is the problem in the documentation?

In the Obsidian URI page, I wonder whether the `clipboard` parameter is in the wrong section?

It is in the `Open note` section, which appears not to use `content`.

And the `content` parameter is documented under `Create note`

I hope this picture helps to explain:

<img width="522" alt="image" src="https://github.com/user-attachments/assets/578626f5-57a5-4727-832c-9bbbe8692ace" />

## Any suggested fixes?
_If it were you handling this issue, what would you do to fix it?_

Maybe move the `clipboard` parameter docs down to below the `content` parameter docs in the next section?

# Have any context we can refer to?

_For example, a Discord link, an existing doc site, etc._

https://help.obsidian.md/Extending+Obsidian/Obsidian+URI

**Comment by kepano** [comment]
Fixed, thanks!
